### ISSUE TITLE
new rule: single line block comment

### ISSUE THREAD

**Issue by HamletDRC** [Microsoft/tslint-microsoft-contrib#115]
All single line block comments should be // comments instead

    /* this is pointless and only causes problems in nesting */
    // this is how single line comments should look

**Comment by reversi-fun** [comment]
I think that's a good idea.
But, for a friendly against vocode-tslint, please be aware of the performance.

The performance of the following TSLint-buildin-rules was slower than {`no-regex-spaces` or `no-constant-condition` }.

{`whitespace`,`no-trailing-whitespace`,`no-consecutive-blank-lines`,`jsdoc-format`,`comment-format`}

Maybe,  Lint.scanAllTokens(ts.createScanner） is 10 times slower than traversing  the AST-node.
Maybe ,Lint.scanAllTokens  will cause many garbage collection.

I expect to Youres exemplary code that is better use of "typescript language service API".

**Comment by dsifford** [comment]
@HamletDRC Is it expected behavior that this rule flags single line block comments in jsx as an error? This is usually the only way to go about making comments within jsx on a single line.

This is especially hindering when you need to insert a `prettier-ignore` or `tslint:disable-nest-line` statement somewhere within jsx.

Example...

```tsx
const Thing = () => 
  <div>
    {/* insert some meaningful comment or ignore statement here */}
    Foo
</div>

**Comment by astorije** [comment]
👋 It would be nice indeed if that rule was not flagging JSX comments `{/* ... */}`.

**Comment by astorije** [comment]
Is this issue resolved with https://github.com/Microsoft/tslint-microsoft-contrib/commit/766aaa6465e69fdb909bf04c2a5db6d476d67bd0 ?

**Comment by JoshuaKGoldberg** [comment]
It should be 🙌
