### ISSUE TITLE
NPM 2.0.3 release?

### ISSUE THREAD

**Issue by chrismbarr** [Microsoft/tslint-microsoft-contrib#116]
I see [the tag for NPM version 2.0.3](https://github.com/Microsoft/tslint-microsoft-contrib/releases/tag/npm-2.0.3), but the [NPM page is still showing version 2.0.2](https://www.npmjs.com/package/tslint-microsoft-contrib).  Was it published correctly to NPM, or does it normally take a day or longer to show up?

**Comment by HamletDRC** [comment]
The Microsoft Org does the publishing so it takes a day or so. I will ask them again.

**Comment by brndkfr** [comment]
available now.
