### ISSUE TITLE
new rule: mocha-done-error-handling

### ISSUE THREAD

**Issue by HamletDRC** [Microsoft/tslint-microsoft-contrib#151]
MochaDone will crash PhanomJS - Very Important! If you do any asynchronous work (like in a setTimeout) then any Mocha failure will cause PhantomJS to crash with the timeout error. You _must_ clear MochaDone on all code paths to fix this! For example, here is some typical MochaDone code: 

```
// THIS CODE IS BROKEN
it('should …', (done: MochaDone): void => {
    setTimeout((): void => {
        // if expect fails then PhantomJS crashes!!!
        expect(something).to.equal(someOtherValue);
        done();
    });
});
```

Here is how you must write the code correctly using a try catch block: 

```
it('should …', (done: MochaDone): void => {
    setTimeout((): void => {
        try {
            expect(something).to.equal(someOtherValue);
            done();
        } catch (e) {
            done(e)
        }
    });
});
```

**Comment by JoshuaKGoldberg** [comment]
@HamletDRC is this still applicable? I don't remember having this error writing tests with Mocha+PhantomJS in late 2017.
