### ISSUE TITLE
Is `no-missing-visibility-modifiers` a dupe of `member-access` in the main project?

### ISSUE THREAD

**Issue by chrismbarr** [Microsoft/tslint-microsoft-contrib#152]
This project has the rule `no-missing-visibility-modifiers`, but [the main TSLint project](https://github.com/palantir/tslint#core-rules) has the rule `member-access`. To me they seem to do the same thing. but are they different?

For what it's worth I find the error messages produced by `no-missing-visibility-modifiers` a lot easier to understand, so I usually leave this rule enabled and I disable `member-access`.

Compare [memberAccessRule.ts](https://github.com/palantir/tslint/blob/master/src/rules/memberAccessRule.ts#L20-L23) to [noMissingVisibilityModifiersRule.ts](https://github.com/Microsoft/tslint-microsoft-contrib/blob/master/src/noMissingVisibilityModifiersRule.ts#L19)

If these 2 rules really do the same thing, it might be worth deprecating this rule and then making a PR to the main TSLint project to make the error report easier to understand.

**Comment by HamletDRC** [comment]
thanks, i updated the docs!
