### ISSUE TITLE
new rule: locally created lambda/bind result used as TSX property

### ISSUE THREAD

**Issue by HamletDRC** [Microsoft/tslint-microsoft-contrib#157]
new rule: locally created lambda/bind result used as TSX property

new lambdas are not equals to the old lambda value... so the is a new property and triggers a React re-render. If you pass a function as a TSX property then it should be a non-changing attribute like a field or method with 'this' bound correctly. 

c @JoshuaKGoldberg I think you guys are using React as well.

**Comment by JoshuaKGoldberg** [comment]
Only on personal use for me :) but that could rule is definitely useful.
