### ISSUE TITLE
new rule: add config parameters to missing-jsdoc rule

### ISSUE THREAD

**Issue by ian-craig** [Microsoft/tslint-microsoft-contrib#162]
While `jsdoc-format` is enough to require correct formatting of docs, there’s no rule that I know of to ensure the docs exist in the first place. It would be useful to have a rule that requires they exist and not be blank for a configurable list of major items (default to everything?), such as:
- classes
- exported variables
- functions
- member variables
- member functions
- ...anything else?

**Comment by HamletDRC** [comment]
Thanks for the idea. This is very similar to #33. I will close that one as a duplicate. 

* Modules
* exported classes
* all classes
* exported variables
* functions
* exported functions
* public member variables
* all member variables
* public member methods
* all member methods

**Comment by JoshuaKGoldberg** [comment]
From a limited TSLint knowledge and reading https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API, I think this requires the type checker for `symbol.getDocumentationComment()`. Yes?

**Comment by HamletDRC** [comment]
@JoshuaKGoldberg I am pretty sure you can get the comments without using the type checker... but if you use the type checker then you probably get a much more structured object and would not have to use RegEx to pick apart the comment. Your suggestion is probably the way to go.

**Comment by JoshuaKGoldberg** [comment]
@ian-craig I think this issue is resolved?
