### ISSUE TITLE
potential depreciation: no-unused-imports

### ISSUE THREAD

**Issue by chrismbarr** [Microsoft/tslint-microsoft-contrib#164]
The `no-unused-variable` rule in the main TSLint project seems to also catch the same things that `no-unused-imports` does in this project.  When I have an unused import, I normally get a failure message for each rule.

**Comment by HamletDRC** [comment]
Hi Chris, thanks for taking the time to file this. 

the no-unused-imports rule finds many, many more unused imports than the no-unused-variable rule. I just ran the rule on the MSE project and it finds over 200 unused imports that the tslint rule did not find (we turned the no-unused-imports rule off thinking it was a duplicate as well, but clearly it was not). 

I suggest you still turn our rule on. 

I will update the readme and file some bugs in tslint

**Comment by HamletDRC** [comment]
Here is the tslint issue I created https://github.com/palantir/tslint/issues/1359

**Comment by HamletDRC** [comment]
updated readme

**Comment by HamletDRC** [comment]
Hi Chris, I just realized that we had an error in our configuration and were accidentially turning the no-unused-variable rule off. The no-unused-imports rule is indeed a duplicate and I will deprecate it.
