### ISSUE TITLE
new rule:unused field in class

### ISSUE THREAD

**Issue by HamletDRC** [Microsoft/tslint-microsoft-contrib#165]
new rule:unused field in class

**Comment by reversi-fun** [comment]
I have question.
Is it a rule to increase the resolution of the message of noUnusedVariableRule?
Is it intended to replace the noUnusedVariableRule?  
https://github.com/palantir/tslint/blob/master/src/rules/noUnusedVariableRule.ts

**Comment by HamletDRC** [comment]
Since fields are not variables, I think this deserves its own rule.

**Comment by chrismbarr** [comment]
When you say "field" do you mean a class constructor parameter?  If not, can you give a code sample of what you mean?

**Comment by HamletDRC** [comment]
This should trigger an error: 

    class MyClass {
        private myField;
        constructor(myField) {
            this.myField = myField;
        }
    }

myField is never referenced. 

It is possible that noUnusedVariableRule already does this. The documentation claims it does. I will have to test it out.

**Comment by HamletDRC** [comment]
closing this as it is covered by the no-unused-variable rule.
