### ISSUE TITLE
new rule: indentation

### ISSUE THREAD

**Issue by shyr1punk** [Microsoft/tslint-microsoft-contrib#167]
Why tslint-microsoft-contrib dont support formatting rules (first line intendation, spaces between braces, etc)? And what you can recommend to use for formatting style check?

**Comment by reversi-fun** [comment]
I think  , The reason is that because have not found the solution of the performance problem .

The performance of the following TSLint-buildin-rules was slower than {no-regex-spaces or no-constant-condition }.
--formatting rules:{whitespace,no-trailing-whitespace,no-consecutive-blank-lines,jsdoc-format,comment-format}

Thease formatting  rules using Lint.scanAllTokens(ts.createScanner). 
And Lint.scanAllTokens will cause many garbage collection.
It's slowness  cause  Lower operability of vscode-tslint.

**Comment by HamletDRC** [comment]
It is not a performance issue. There are many existing rules around whitespace. What is it that you need that is not covered by one of the following from the recommended_ruleset.js? 

         "align": [true, "parameters", "arguments", "statements"],
        "curly": true,
        "eofline": true,
        "indent": [true, "spaces"],
        "no-consecutive-blank-lines": true,
        "no-empty-line-after-opening-brace": false,
        "no-trailing-whitespace": true,
        "no-unnecessary-semicolons": true,
        "one-line": [true, "check-open-brace", "check-catch", "check-else", "check-whitespace"],
        "quotemark": [true, "single"],
        "semicolon": [true, "always"],
        // forcing trailing commas for multi-line lists results in lists that are easier to reorder and version
        // control diffs that are more clear. Many teams like to have multiline be 'always'. There is no
        // clear consensus on this rule but the internal MS JavaScript coding standard does discourage it.
        "trailing-comma": [true, {"singleline": "never", "multiline": "never"}],
        "typedef-whitespace": false,
        "whitespace": [true, "check-branch", "check-decl", "check-operator", "check-separator", "check-type"],

**Comment by HamletDRC** [comment]
@shyr1punk What exactly is "first line indentation" and "spaces between braces"?

**Comment by shyr1punk** [comment]
@HamletDRC thank for you answer.

I have rules, like you described above.

But I can write somethink like this:

```
/**
* Forms list
*/
import * as    React from 'react';
  import { Link } from 'react-router';
import {   Panel } from     'ufs-ui';   

export   class Forms    extends React.Component<{}, {}> {
      public render (  ) {
return (
   <Panel block header='Forms'>
      <Link   to='/forms/dashboard'>Dashboard</Link>
</Panel>
  );
  }
}
```

tslint result:
```
$ tslint -t verbose -c tslint.json app/**/*.tsx
(no-trailing-whitespace) app/forms/Forms.tsx[6, 38]: trailing whitespace
(no-trailing-whitespace) app/forms/Forms.tsx[16, 2]: trailing whitespace
```

I expect the rules to work like http://eslint.org/docs/2.0.0/rules/indent

**Comment by HamletDRC** [comment]
Do you need all those options? Or can we just do 4 spaces? 
Do you need this VariableDeclarator stuff? I don't.

I'm going to change the title to "new rule: indentation"

**Comment by HamletDRC** [comment]
By the way, there are a couple more formatting rules here: https://github.com/buzinas/tslint-eslint-rules/tree/master/src/rules

But I think this repo is a bit more active than that one.

**Comment by shyr1punk** [comment]
> Do you need all those options?

You talk about all of eslint formatting options? Or about 3 options from example?

What I want? I want a rules, that define strict and the only sure way for formatting code. Want a lot of programmers on a project can create the same formatted code and automaticly check that in code editor and pre-commit hook. That avoid a random edits.

I have a experience of using a ESLint with AirBnB rules. It helps a write readable and same formatted code by different programmers. I think it's a part of a enterprise software development. I take a part in a big project without strict formatting rules - the code looks urgy. Difficult to read, everyone want a change formatting of existing code at its discretion. Causing big formatting (not actual changed functionality) differenses in a commit diffs. Not all of us consciously react to same formatting.

And those options must be a configurable: for example 2 or 4 spaces for indentation.

Probably formatting rules should be in another rules set (or exists in eslint-tslint-rules).

**Comment by HamletDRC** [comment]
The rule makes sense to me. I'll leave this issue open. 

By options... I meant, "do you need all the options that the eslint rule has". I think that simply enforcing the indentation level would be 90% of the value of the rule. Then you have all those hanging indent edge cases. 

You might try opening a similar issue on the tslint project. They often reject rule ideas though if it doesn't fit with their usages. 

I'll leave this open and see if I can get to it. It is a good idea.

**Comment by JoshuaKGoldberg** [comment]
@shyr1punk since this was posted, Prettier has become very popular and the core TSLint project has started to advise usage of it. I can vouch that it's a _very_ nice experience if you haven't tried it out yet.

Closing this issue as external, as Prettier can format with more power & speed than TSLint. Thanks for posting!
