### ISSUE TITLE
NPM Release

### ISSUE THREAD

**Issue by mike-morrison** [Microsoft/tslint-microsoft-contrib#177]
Do you have an ETA for the TS 2.0 support making it into NPM?

**Comment by HamletDRC** [comment]
Hi @mike-morrison , 

The latest version is on our branch called "releases". So you should be able to point your npm dependency to that branch to get the latest. https://github.com/Microsoft/tslint-microsoft-contrib/tree/releases

I'll start the release process now though. The OSS group in Seattle does the actual publish so it can take up to 24 hours to hit npm.
