### ISSUE TITLE
new rule: unneeded mocha done

### ISSUE THREAD

**Issue by HamletDRC** [Microsoft/tslint-microsoft-contrib#179]
If an it/describe/before/after function takes a MochaDone parameter, then it should really be needed. 

Create a violation if: 
* a mocha lifecycle function declares a mocha done parameter
* the done parameter never escapes the method (as a parameter to a function, for example)
* the done object is only invoked once as the last line of the function

**Comment by michalzubkowicz** [comment]
Isn't it causing false positive when async/await is used?
