### ISSUE TITLE
Export TestHelper?

### ISSUE THREAD

**Issue by ipip2005** [Microsoft/tslint-microsoft-contrib#184]
This is not actually an issue.

The TestHelper.ts file under tests folder is really useful, can it be exported so we can use it in our project?

**Comment by HamletDRC** [comment]
I can, but...
* it depends on fs from node (so it does not work in the browser)
* it assumes all files are utf-8 encoded (so you'd better have the correct encoding on your files)
* it would mean exporting the d.ts file 

Do you really want it exported?

**Comment by HamletDRC** [comment]
Also, feel free to submit your rules here as a feature request!

**Comment by ipip2005** [comment]
Yes, it would be helpful, I would use this file to test my customized rules.
One problem is the `rulesDirectroy` and `formatterDirectory` is hard coded, I can only use it if I can specify this option.
And thanks for your offer, I just started working on some react-accessibility rules, waiting for more feedbacks from our project team.

**Comment by HamletDRC** [comment]
OK, I will export this class. I am also working on some React accessibility rules. I would very much like to hear your ideas. I am going to open a different issue and cc you for a discussion!

**Comment by ipip2005** [comment]
Cool, Great to hear, Thanks!

**Comment by HamletDRC** [comment]
OK, the npm package is now on the https://github.com/Microsoft/tslint-microsoft-contrib/tree/releases

Do you need an npm deployment to use this? Or can you point your package.json at this project's releases branch?

**Comment by ipip2005** [comment]
Perhaps I need a npm deployment to use it for our check-in procedure. I would use this releases branch for testing first.
Thank you so much!
