### ISSUE TITLE
Add tslint.json to npm release

### ISSUE THREAD

**Issue by tpetry** [Microsoft/tslint-microsoft-contrib#190]
It would be really helpfully if the recommended tslint.json would be added to the npm release so build scripts could directly reference the tslint.json of the release instead of having to merge the actual version from github everytime to a local copy.

**Comment by HamletDRC** [comment]
Do you want the file recommended_ruleset.js (which is a .js file?)
Or do you want the recommended_ruleset.js to be converted to JSON and copied as the file tslint.json?

**Comment by tpetry** [comment]
The tslint.json. It is included in the normal release tags but not the release tags for npm.

**Comment by HamletDRC** [comment]
I can put this in the deployment, but what do you want it for? It is just some rules that we use internally on the project and it is not how we recommend other projects be configured. It seems like what you actually want it recommended_ruleset.js.

**Comment by tpetry** [comment]
Then maybe it would be better to convert it to recommened_ruleset.json for the npm release.

**Comment by HamletDRC** [comment]
I think this is the file you want: https://github.com/Microsoft/tslint-microsoft-contrib/blob/master/recommended_ruleset.js

**Comment by HamletDRC** [comment]
Here is the link to the recommended_ruleset.js
https://github.com/Microsoft/tslint-microsoft-contrib/blob/master/recommended_ruleset.js

**Comment by HamletDRC** [comment]
There are some tools that will see tslint.json and by default use that... so perhaps there is value in renaming the thing to tslint.json.
