### ISSUE TITLE
Version is 2.0.9 on npm

### ISSUE THREAD

**Issue by kylelamse** [Microsoft/tslint-microsoft-contrib#192]
Whenever installing doing a default npm install, 2.0.9 will be installed instead of 2.0.10

**Comment by HamletDRC** [comment]
This is because the README.md file is displayed from the master (development) branch, which is always 1 release ahead of the npm deployment. I updated the readme to clarify the version numbers. 

I am making the 2.0.10 release right now. 

thanks,
