### ISSUE TITLE
new rule: must-throw-error-type

### ISSUE THREAD

**Issue by HamletDRC** [Microsoft/tslint-microsoft-contrib#202]
new rule: must-throw-error-type

Only throw the type Error. Throwing a string can break error handling code. 

```
// OK
throw new Error('...')
throw new CustomError('...')
catch (e) { throw e; }

// bad
throw 'an error occurred';
throw someUnknownThing;
```

**Comment by reversi-fun** [comment]
Ohh! fine!
I wonder that is blocked by the type checker?

```
import util = require("util");
 util.init();  // it execcutes "util.errorCode = new new CustomError('...');"

throw util.errorCode; // is it ok? or BAD?
```

**Comment by HamletDRC** [comment]
Yes, we need the type checker to accurately know if the the thrown object is an error or not.

**Comment by JoshuaKGoldberg** [comment]
https://palantir.github.io/tslint/rules/no-string-throw/ ✨ 👍
