### ISSUE TITLE
Update react-a11y-img-has-alt - img alt prop must not contain the word "image", "picture", or "photo"

### ISSUE THREAD

**Issue by HamletDRC** [microsoft/tslint-microsoft-contrib#219]
Enforce img alt attribute does not contain the word image, picture, or photo. Screenreaders already announce img elements as an image. There is no need to use words such as image, photo, and/or picture.

img alt prop must not contain the word "image", "picture", or "photo"
accept some parameters here and allow configuration
not case sensitive!

**Comment by JoshuaKGoldberg** [comment]
☠️  *It's time!* ☠️ 

Per #876, this repository is no longer accepting feature pull requests. TSLint is being deprecated and we recommend you switch to https://typescript-eslint.io.

Thanks for open sourcing with us, everyone!
