### ISSUE TITLE
Update react-a11y-img-has-alt - An 'alt' attribute should contain {0} or fewer characters

### ISSUE THREAD

**Issue by HamletDRC** [microsoft/tslint-microsoft-contrib#220]
An 'alt' attribute should contain {0} or fewer characters. (Warnings Central)

**Comment by JoshuaKGoldberg** [comment]
☠️  *It's time!* ☠️ 

Per #876, this repository is no longer accepting feature pull requests. TSLint is being deprecated and we recommend you switch to https://typescript-eslint.io.

Thanks for open sourcing with us, everyone!
