### ISSUE TITLE
Update react-a11y-img-has-alt - Object elements must contain a text alternative 

### ISSUE THREAD

**Issue by HamletDRC** [microsoft/tslint-microsoft-contrib#222]
Object elements must contain a text alternative after all other alternatives are exhausted. "Object element (or group of nested object elements) that does not contain a text alternative at the deepest level. Message will fire on the innermost Object element." http://www.w3.org/TR/WCAG20-TECHS/H53 - axe-core - object-alt - wcag2a, wcag111, section508, section508.22.a

**Comment by JoshuaKGoldberg** [comment]
Per #876, this repository is no longer accepting pull requests. ☠️
