### ISSUE TITLE
Expand react-a11y-role-supports-aria-props - Check that enabled elements with ACTIVE-DESCENDANT have valid tab index

### ISSUE THREAD

**Issue by HamletDRC** [microsoft/tslint-microsoft-contrib#225]
Expand react-a11y-role-supports-aria-props - Check that enabled elements with ACTIVE-DESCENDANT have valid tab index
- http://oaa-accessibility.org/wcag20/rule/96/

**Comment by JoshuaKGoldberg** [comment]
Per #876, this repository is no longer accepting pull requests. ☠️
