### ISSUE TITLE
Expand react-a11y-role-supports-aria-props - Check that elements without 'aria-activedescendant' that have roles requiring a container have key event handlers

### ISSUE THREAD

**Issue by HamletDRC** [microsoft/tslint-microsoft-contrib#226]
Expand react-a11y-role-supports-aria-props - Check that elements without 'aria-activedescendant' that have roles requiring a container have key event handlers
- http://oaa-accessibility.org/wcag20/rule/98/

**Comment by JoshuaKGoldberg** [comment]
Per #876, this repository is no longer accepting pull requests. ☠️
