### ISSUE TITLE
Expand react-a11y-role-supports-aria-props - Check that elements without 'aria-activedescendant' that have roles requiring a container have focusable children

### ISSUE THREAD

**Issue by HamletDRC** [microsoft/tslint-microsoft-contrib#227]
Expand react-a11y-role-supports-aria-props - Check that elements without 'aria-activedescendant' that have roles requiring a container have focusable children
- http://oaa-accessibility.org/wcag20/rule/97/

**Comment by JoshuaKGoldberg** [comment]
☠️  *It's time!* ☠️ 

Per #876, this repository is no longer accepting feature pull requests. TSLint is being deprecated and we recommend you switch to https://typescript-eslint.io.

Thanks for open sourcing with us, everyone!
