### ISSUE TITLE
Expand react-a11y-role-supports-aria-props - Roles must contain their required child roles

### ISSUE THREAD

**Issue by HamletDRC** [microsoft/tslint-microsoft-contrib#228]
Expand react-a11y-role-supports-aria-props - Roles must contain their required child roles
- http://oaa-accessibility.org/wcag20/rule/88/

**Comment by JoshuaKGoldberg** [comment]
☠️  *It's time!* ☠️ 

Per #876, this repository is no longer accepting feature pull requests. TSLint is being deprecated and we recommend you switch to https://typescript-eslint.io.

Thanks for open sourcing with us, everyone!
