### ISSUE TITLE
Expand react-a11y-role-supports-aria-props - Child roles must be contained by the proper parent role

### ISSUE THREAD

**Issue by HamletDRC** [microsoft/tslint-microsoft-contrib#229]
Expand react-a11y-role-supports-aria-props - Child roles must be contained by the proper parent role
- http://oaa-accessibility.org/wcag20/rule/89/

**Comment by JoshuaKGoldberg** [comment]
☠️  *It's time!* ☠️ 

Per #876, this repository is no longer accepting feature pull requests. TSLint is being deprecated and we recommend you switch to https://typescript-eslint.io.

Thanks for open sourcing with us, everyone!
