### ISSUE TITLE
new security rule: detect-unsafe-regex

### ISSUE THREAD

**Issue by HamletDRC** [microsoft/tslint-microsoft-contrib#250]
Check if the regex is evil or not using the safe-regex module

https://github.com/nodesecurity/eslint-plugin-security/blob/master/rules/detect-unsafe-regex.js

**Comment by HamletDRC** [comment]
Also cover this scenario: 
https://github.com/nodesecurity/eslint-plugin-security/blob/master/rules/detect-non-literal-regexp.js

This needs to be expanded in logic a little.

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated**; therefore, it and tslint-microsoft-contrib are no longer accepting pull requests for major new changes or features. See #4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint or tslint-microsoft-contrib locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
