### ISSUE TITLE
TestHelper fail in version 2.0.12

### ISSUE THREAD

**Issue by ipip2005** [Microsoft/tslint-microsoft-contrib#270]
One line in TestHelper.ts
import {ErrorTolerantWalker} from '../src/utils/ErrorTolerantWalker';
compiled to 
var ErrorTolerantWalker_1 = require('../src/utils/ErrorTolerantWalker');
in node_modules, but path `../src/utils/ErrorTolerantWalker` is not valid, thus the build break when we try to consume this project.

**Comment by HamletDRC** [comment]
Fix is on the @releases branch. Can you try that dependency and make sure it works?

**Comment by ipip2005** [comment]
Thanx for this fix, seems the whole `test` folder moved to `src`. It should work now.
