### ISSUE TITLE
new a11y rule: no obsolete html 

### ISSUE THREAD

**Issue by HamletDRC** [microsoft/tslint-microsoft-contrib#273]
https://www.w3.org/TR/html5/obsolete.html

Obsolete but conforming features: Features listed in this section will trigger warnings in conformance checkers
- Authors should not specify a border attribute on an img element. 
- Authors should not specify a language attribute on a script element
- Authors should not specify the name attribute on a elements
- Authors should not specify the maxlength and size attributes on input elements whose type attributes are in the Number state. 
- no 'big' element 
  From https://github.com/globant-ui/arialinter/blob/master/lib/rules/element.js
  • do not use 'u' element (http://oaa-accessibility.org/rule/71/)
  • do not use 'i' element (http://oaa-accessibility.org/rule/70/)
  • do not use 'b' element (http://oaa-accessibility.org/rule/69/')
- charset on a elements
- charset on link elements
- coords on a elements
- shape on a elements
- methods on a elements
- methods on link elements
- name on a elements
- name on embed elements
- name on img elements
- name on option elements
- urn on a elements
- urn on link elements
- accept on form elements
- nohref on area elements
- profile on head elements
- version on html elements
- ismap on input elements
- usemap on input elements
- lowsrc on img elements
- target on link elements
- scheme on meta elements
- archive on object elements
- classid on object elements
- code on object elements
- codebase on object elements
- codetype on object elements
- declare on object elements
- standby on object elements
- type on param elements
- valuetype on param elements
- language on script elements (except as noted in the previous section)
- event on script elements
- for on script elements
- datapagesize on table elements
- summary on table elements
- axis on td and th elements
- scope on td elements
- datasrc on a, applet, button, div, frame, iframe, img, input, label, legend, marquee, object, option, select, span, table, and textarea elements
- datafld on a, applet, button, div, fieldset, frame, iframe, img, input, label, legend, marquee, object, param, select, span, and textarea elements
- dataformatas on button, div, input, label, legend, marquee, object, option, select, span, and table elements
- alink on body elements
- bgcolor on body elements
- link on body elements
- marginbottom on body elements
- marginheight on body elements
- marginleft on body elements
- marginright on body elements
- margintop on body elements
- marginwidth on body elements
- text on body elements
- vlink on body elements
- clear on br elements
- align on caption elements
- align on col elements
- char on col elements
- charoff on col elements
- valign on col elements
- width on col elements
- align on div elements
- compact on dl elements
- align on embed elements
- hspace on embed elements
- vspace on embed elements
- align on hr elements
- color on hr elements
- noshade on hr elements
- size on hr elements
- width on hr elements
- align on h1—h6 elements
- align on iframe elements
- allowtransparency on iframe elements
- frameborder on iframe elements
- hspace on iframe elements
- marginheight on iframe elements
- marginwidth on iframe elements
- scrolling on iframe elements
- vspace on iframe elements
- align on input elements
- hspace on input elements
- vspace on input elements
- align on img elements
- border on img elements
- hspace on img elements
- vspace on img elements
- align on legend elements
- type on li elements
- align on object elements
- border on object elements
- hspace on object elements
- vspace on object elements
- compact on ol elements
- align on p elements
- width on pre elements
- align on table elements
- bgcolor on table elements
- bordercolor on table elements
- cellpadding on table elements
- cellspacing on table elements
- frame on table elements
- rules on table elements
- width on table elements
- align on tbody, thead, and tfoot elements
- char on tbody, thead, and tfoot elements
- charoff on tbody, thead, and tfoot elements
- valign on tbody, thead, and tfoot elements
- align on td and th elements
- bgcolor on td and th elements
- char on td and th elements
- charoff on td and th elements
- height on td and th elements
- nowrap on td and th elements
- valign on td and th elements
- width on td and th elements
- align on tr elements
- bgcolor on tr elements
- char on tr elements
- charoff on tr elements
- valign on tr elements
- compact on ul elements
- type on ul elements
- background on body, table, thead, tbody, tfoot, tr, td, and th elements

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated**; therefore, it and tslint-microsoft-contrib are no longer accepting pull requests for major new changes or features. See #4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint or tslint-microsoft-contrib locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
