### ISSUE TITLE
new a11y rule: accessible onclick

### ISSUE THREAD

**Issue by HamletDRC** [microsoft/tslint-microsoft-contrib#277]
onclick-has-focus
Enforce that elements with onClick handlers must be focusable.
    • http://oaa-accessibility.org/wcag20/rule/61/

onclick-has-role
Check that non-form and non-anchor elements with event handlers have valid roles.
    • http://oaa-accessibility.org/wcag20/rule/94/

Reference: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role

Alternative: 
Enforce that non-interactive, visible elements (such as `<div>`) that have click handlers use the role attribute.

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated**; therefore, it and tslint-microsoft-contrib are no longer accepting pull requests for major new changes or features. See #4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint or tslint-microsoft-contrib locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
