### ISSUE TITLE
new a11y rule: Required input elements must define aria-required="true" 

### ISSUE THREAD

**Issue by HamletDRC** [Microsoft/tslint-microsoft-contrib#280]
Required input elements must define aria-required="true" 

http://www.clarissapeterson.com/2012/11/html5-accessibility/

**Comment by cTxplorer** [comment]
@JoshuaKGoldberg Is there a specific file to be updated? Or all of the files in the repo?

**Comment by cTxplorer** [comment]
@JoshuaKGoldberg Can you help with the issue - how can I contribute here? Is there a specific file to be updated? Or all of the files in the repo?

**Comment by cTxplorer** [comment]
@JoshuaKGoldberg Great help. Thanks!

**Comment by jcnsilva** [comment]
Hi, @cTxplorer , are you still working on this issue?

**Comment by jcnsilva** [comment]
@JoshuaKGoldberg can I submit a pr for this issue?

**Comment by JoshuaKGoldberg** [comment]
@jcnsilva sure, go ahead. > a couple of weeks seems like a good amount of time to wait.

**Comment by cTxplorer** [comment]
@jcnsilva No I'm not working on this issue. Sorry, for late response! 
Great work, btw.
