### ISSUE TITLE
expand react-a11y-proptypes: full support for all rules

### ISSUE THREAD

**Issue by HamletDRC** [microsoft/tslint-microsoft-contrib#281]
expand react-a11y-proptypes: full support for all rules

Enforce ARIA state and property values are valid.
    • https://www.w3.org/TR/wai-aria/states_and_properties
    • http://oaa-accessibility.org/wcag20/rule/85/

ARIA ID references must be valid IDRefs
    • http://oaa-accessibility.org/wcag20/rule/86/

aria-owns should not be used if ownership is implicit in the DOM
    • https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#aria-owns-should-not-be-used-if-ownership-is-implicit-in-the-dom

An element's ID must not be present in more than one aria-owns attribute at any time
    • https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#an-elements-id-must-not-be-present-in-more-than-one-aria-owns-attribute-at-any-time

Elements with ARIA roles must ensure required owned elements are present
    • https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#elements-with-aria-roles-must-ensure-required-owned-elements-are-present

Elements with ARIA roles must be in the correct scope
    • https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#elements-with-aria-roles-must-be-in-the-correct-scope

**Comment by JoshuaKGoldberg** [comment]
☠️  *It's time!* ☠️ 

Per #876, this repository is no longer accepting feature pull requests. TSLint is being deprecated and we recommend you switch to https://typescript-eslint.io.

Thanks for open sourcing with us, everyone!
