### ISSUE TITLE
NoStringBasedSetTimeoutTests false positive

### ISSUE THREAD

**Issue by anvish** [microsoft/tslint-microsoft-contrib#285]
new Promise(resolve => window.setTimeout(resolve, 100))

**Comment by HamletDRC** [comment]
The typechecker used in tslint is by default not aware of types. (it doesn't do much at all). So even though eslib.d.ts defines resolve as a function type, the tslint rule has no idea what the type of `resolve` is.

What we need to do to fix this is: 

* change the rule to require the "tslint program as a whole" feature (see https://github.com/palantir/tslint/issues/680)
* change the rule to use the updated typechecker

I will tag this "blocked on typechecker"

**Comment by connor4312** [comment]
I'm unsure if this is the same core issue, but this rule has issue with calls to [`request.setTimeout`](https://nodejs.org/api/http.html#http_request_settimeout_timeout_callback) as well.

**Comment by HamletDRC** [comment]
Yes, it is the same issue. Our current approach is to be "better safe than sorry" and flag anything that is clearly not a function. We plan to upgrade the rule at some point. We just had a big push to get a bunch of accessibility rules done, so I think everyone is taking a small break before giving it some more effort.

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is deprecated** and no longer accepting pull requests other than security fixes. See #876. ☠️ 
We recommend you instead use **[typescript-eslint](https://typescript-eslint.io)** to lint your TypeScript code with **ESLint**. ✅

👋 It was a pleasure open sourcing with you!
