### ISSUE TITLE
new rule: no variable hoisting

### ISSUE THREAD

**Issue by HamletDRC** [Microsoft/tslint-microsoft-contrib#29]
Avoid situations that would result in variable hoisting.

**Comment by danielmanesku** [comment]
Explanation what variable hoisting is: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var#var_hoisting

**Comment by HamletDRC** [comment]
I am closing this as "won't fix". 
All devs should use let and const declarations so that this problem does not occur.
