### ISSUE TITLE
new security rule: window.open opener is not null

### ISSUE THREAD

**Issue by HamletDRC** [microsoft/tslint-microsoft-contrib#293]
https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

If you use window.open then you must do this: 

```typescript
let newWnd = window.open();
newWnd.opener = null;
```

**Comment by knrt10** [comment]
@JoshuaKGoldberg I would like to work on this issue.

**Comment by JoshuaKGoldberg** [comment]
Awesome, great to hear @knrt10!

Unfortunately, it looks like there's a bug in the TypeScript typings in this area: see https://github.com/Microsoft/TSJS-lib-generator/issues/577. I'll mark this rule as blocked until that's resolved. Sorry for bait and switching here!

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated**; therefore, it and tslint-microsoft-contrib are no longer accepting pull requests for major new changes or features. See #4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint or tslint-microsoft-contrib locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
