### ISSUE TITLE
Publish a 2nd recommended ruleset that contains *only* the contrib rules

### ISSUE THREAD

**Issue by dsifford** [microsoft/tslint-microsoft-contrib#309]
Hello there,

I'm in a situation I'd like to be able to pull and use the bleeding edge code from the master branch (specifically, because in `2.0.13`, still having `no-duplicate-key` set to true is breaking my build).

Would this be possible? 

Thanks so much.

**Comment by dsifford** [comment]
An alternative to this would be to strip out all rules not residing in this project from the `tslint.json` file.

Users who `"extends": ["tslint-microsoft-contrib"]` may not be aware that by extending this project, they're also extending `tslint` proper.

**Comment by HamletDRC** [comment]
@dsifford have you tried using our "releases" branch? It is the latest compiled code. Does that fix the issue 

I'm not sure how having the source code in the /dist dir solves your problem. 

(sorry, I thought I'd replied to this earlier).

**Comment by dsifford** [comment]
@HamletDRC No worries.

No, the releases branch did not work for me. I'm using the nightly branch of tslint and that was not cooperating with the fact that if I `extend` your releases branch, I'd also be extending the `no-duplicate`key` rule from tslint proper (which is set in your tslint.json).

I think the main issue is that this repo creates a circumstance that results in an "extends cascade". In other words, if I extend this repo, I'm also extending all the repos that you extend (or, in this case, the rules from tslint proper that you have set in your `tslint.json` file).

I ended up just removing the extends rule for this repo from my project for now until your tslint.json is free of the `no-duplicate-key` rule.

(I hope that makes sense. It's admittedly a bit confusing).

**Comment by HamletDRC** [comment]
@dsifford so your problem would be solved if we published a 2nd tslint.json that only contained our rules, right?

**Comment by dsifford** [comment]
Correct

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is deprecated** and no longer accepting pull requests other than security fixes. See #876. ☠️ 
We recommend you instead use **[typescript-eslint](https://typescript-eslint.io)** to lint your TypeScript code with **ESLint**. ✅

👋 It was a pleasure open sourcing with you!
