### ISSUE TITLE
Rule suggestion: prefer-readonly

### ISSUE THREAD

**Issue by buu700** [Microsoft/tslint-microsoft-contrib#316]
This would be really nice to have for the same reasons as prefer-const, and I'd imagine the implementation wouldn't be too different.

**Comment by HamletDRC** [comment]
this is a good idea

**Comment by JoshuaKGoldberg** [comment]
Feels like this is a super useful rule that should go in TSLint main. Dup of https://github.com/palantir/tslint/issues/1628?

**Comment by buu700** [comment]
Yeah, this was poor timing on my part; `prefer-const` was added to tslint main two days after I opened this issue (https://github.com/palantir/tslint/pull/1801), and since that rule only existed here at the time I didn't think to check tslint main for duplicates before posting here.
