### ISSUE TITLE
Version 4 not on npm

### ISSUE THREAD

**Issue by bondz** [Microsoft/tslint-microsoft-contrib#323]
Version 4 of this library with support for tslint >=4 isn't yet available on npm.

**Comment by josundt** [comment]
Ditto. Please publish to npm.

**Comment by brndkfr** [comment]
Publishing to npm is managed by an MS admin team. We send out the request for publishing. We have to wait until they push.

**Comment by HamletDRC** [comment]
As @brndkfr said, the release process has started and it in progress

**Comment by Delagen** [comment]
@HamletDRC when is it expected? 1-2 hours, or 1-2 weeks?

**Comment by HamletDRC** [comment]
The npm admins are in the Pacific timezone (Redmond). I expect them to publish by 20:00 GMT.
