### ISSUE TITLE
Rule `no-empty-interfaces` can be deprecated - now in main TSLint

### ISSUE THREAD

**Issue by chrismbarr** [Microsoft/tslint-microsoft-contrib#328]
the [TSLint 4.2.0 release](https://github.com/palantir/tslint/releases/tag/4.2.0) now includes a rule called `no empty-interface` which means the rule in this project (`no-empty-interfaces`) can likely be depricated now.

relevant PR: https://github.com/palantir/tslint/pull/1889
docs: https://palantir.github.io/tslint/rules/no-empty-interface/

**Comment by HamletDRC** [comment]
the referenced bug is closed
