### ISSUE TITLE
new rule: all exported/public members should have jsdoc rule

### ISSUE THREAD

**Issue by HamletDRC** [Microsoft/tslint-microsoft-contrib#33]
add parameters to the missing-jsdoc rule to turn on/off: 
* public methods
* exported functions
* public fields
* exported vars
* exported classes
* what else?

**Comment by reversi-fun** [comment]
>what else?

Oh. I  have request.
+  It is not important that it is a jsdoc("/**")
+  function documents ;
  PropertyAssignment-ArrowFunction, VariableDeclaration-ArrowFunction,let-ArrowFunction
 PropertyAssignment-FunctionExpression,VariableDeclaration-FunctionExpression,let-FunctionExpression

+  missing parm infomation to be reports.
+  missing event ( excepts when calling)  infomation to be reports.
+  missing return infomation (return value to return type is not explicitly defined) to be reports.

**Comment by reversi-fun** [comment]
https://github.com/reversi-fun/tslint-microsoft-contrib/blob/reversi-fun-patch2/src/ngFunctionDocRule.ts

**Comment by HamletDRC** [comment]
closing as duplciate of #162
