### ISSUE TITLE
no-http-string hangs on ridiculously huge (JSON?) strings

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/tslint-microsoft-contrib#336]
Fun little "the team's builds just started to hang for no reason" mayday after enabling `no-http-string`. Turns out we had a file with a serialized JSON string 1,466,450 characters long (don't ask). Hanging seems to start whenever a string is over about 200k characters.

We tested out using a simple `indexOf` instead of the regular expression and it stopped hanging.

**Comment by JoshuaKGoldberg** [comment]
I'll rebase the commits to be reasonable if/when the PR gets signoff - working from the web editor...

**Comment by HamletDRC** [comment]
@JoshuaKGoldberg Thank you for taking the time to find and fix these issues!
