### ISSUE TITLE
New Rule: All paths in functions should resolve or reject a Promise

### ISSUE THREAD

**Issue by HamletDRC** [Microsoft/tslint-microsoft-contrib#34]
This is very similar to https://github.com/Microsoft/tslint-microsoft-contrib/issues/26 (https://github.com/Microsoft/tslint-microsoft-contrib/issues/26)

This code is OK because all paths resolve or reject: 

    function myMethod() : Promise<void> {
        return new Promise<void>((resolve, reject) => {
            if (something) {
                resolve()
            } else {
                reject();
            }
        });
    }

This code creates a violation because not all paths resolve/reject: 

    function myMethod() : Promise<void> {
        return new Promise<void>((resolve, reject) => {
            if (something) {
                resolve()
            }
        });
    }

All of the rules for scope, variable shadowing, and type limitations apply from https://github.com/Microsoft/tslint-microsoft-contrib/issues/26

**Comment by arogg** [comment]
Tried second example, does not work with tslint 5.11.0 . Any yes I am using the --type-check and --project option :) Other rules from tslint-microsoft-contrib seem to work.

**Comment by JoshuaKGoldberg** [comment]
Hey @arogg, sorry to hear that! Would you mind [filing a new issue](https://github.com/Microsoft/tslint-microsoft-contrib/issues/new) with the following information:
* File contents _(is it exactly the second example, no modifications?)_
* Link to your project, if it's open source 
* `tslint.json` contents
* How you're running TSLint, such as on the CLI or via the VS Code extension
