### ISSUE TITLE
new rule: mocha - no nested it() functions

### ISSUE THREAD

**Issue by HamletDRC** [microsoft/tslint-microsoft-contrib#340]
Mocha allows you to nest describe() functions, and to put it() functions inside describe functions. 

Sometimes developers accidentally put it() functions inside other it() functions. These tests will not run if you do this!

**Comment by JoshuaKGoldberg** [comment]
Could this be extended to be more generic? A rule that prevents described chains of nested functions would be nifty.

```json
{
    "banned-chains": [
        ["it", "it"],
        ["it", "describe"]
    ]
}

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated**; therefore, it and tslint-microsoft-contrib are no longer accepting pull requests for major new changes or features. See #4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint or tslint-microsoft-contrib locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
