### ISSUE TITLE
Recommended value for member-ordering rule is pointless

### ISSUE THREAD

**Issue by Livven** [Microsoft/tslint-microsoft-contrib#341]
The [`recommended_ruleset.js`](https://github.com/Microsoft/tslint-microsoft-contrib/blob/cc2d7f407251d7aee77ea8742edb2ab20639696e/recommended_ruleset.js#L109) includes a `"member-ordering": true` rule which in that form doesn't actually do anything.

See the [documentation](https://palantir.github.io/tslint/rules/member-ordering/).

**Comment by tommck** [comment]
Actually, over 10 of the rules give me linting errors because they expect arrays when the value in the recommended is "true" or "false"

**Comment by Livven** [comment]
@tommck I think that's due to the schema not allowing either an array or a boolean at the same time. It's perfectly valid to disable an option with just a `false` even if enabling it would require an array of parameters.

**Comment by HamletDRC** [comment]
Do any of you have a preferred recommended default value?

@tommck which other rules have invalid default parameters? I am not linting the file, so whether or not you get linting errors depends I guess on what your linting tool and linting rules are.

**Comment by HamletDRC** [comment]
If anyone wants to make a proposed default value then just edit line 143 of this file: https://github.com/Microsoft/tslint-microsoft-contrib/blob/master/additional_rule_metadata.json

I'll accept the pull request that automatically is sent when you click save :)

**Comment by HamletDRC** [comment]
I set the default to [true, { "order": "fields-first" }]

Feel free to change this!
