### ISSUE TITLE
Recommended typedef parameters are camel-cased instead of kebab-cased

### ISSUE THREAD

**Issue by emauricio** [Microsoft/tslint-microsoft-contrib#344]
Hello there :) , quick question about the recommended settings.

Im using Webstorm and latest tslint.

This rule set is on the recommended list, but seems that not trigger anything.
```
"typedef": [true, "callSignature", "indexSignature", "parameter", "propertySignature", "variableDeclarator", "memberVariableDeclarator"],
```

In the rules from [tslint](https://palantir.github.io/tslint/rules/typedef/) is define a little different
and it works.
```
"typedef":` [ true, "call-signature", "parameter", "variable-declaration", "property-declaration",  "member-variable-declaration" ]
```

So i was wondering if Im missing any setting,  is just a typo inside the recommended list or i didn't understood from where that typedef come from . :P

Thank you in advance.

**Comment by HamletDRC** [comment]
You are correct! It is a bug. I suspect maybe the parameter names changed in the last 18 months.
