### ISSUE TITLE
New rule: no space between identifier name and colon when declaring types

### ISSUE THREAD

**Issue by danielmanesku** [Microsoft/tslint-microsoft-contrib#35]
No space after a variable name and before colon when writing type and return declaration.
Right: 

    var quantity: number = 101;

Wrong: 

    var quantity : number = 101;

Right: 

    public getSomething(source: string): string {

Wrong: 

    public getSomething(source : string) : string {

Note: ternary operator explicitly asks for a space before and after semicolon, tsc will complain if you don't put it.

**Comment by HamletDRC** [comment]
this was implemented in tslint's whitespace rule
