### ISSUE TITLE
4.0.1 not released on npm

### ISSUE THREAD

**Issue by noxan** [Microsoft/tslint-microsoft-contrib#351]
Is it just me or is the 4.0.1 release not yet available on npm? Just saw two different tags here on GitHub but looks like none made it to npm [1].

Just came across the issue with dashes in the name today. And I am very glad to see the `import-name` rule fixed already, great work 👍

[1] https://www.npmjs.com/package/tslint-microsoft-contrib 

<img width="350" alt="screen shot 2017-03-17 at 16 24 10" src="https://cloud.githubusercontent.com/assets/536225/24050123/318a5054-0b2e-11e7-839d-15b80b410b97.png">

**Comment by HamletDRC** [comment]
It takes up to 24 hours to make it to npm. I guess I could wait to update the readme until after it hits npm next time.

**Comment by HamletDRC** [comment]
It is there now so I will close this. Thanks for the positive feedback. 

If you want to try making a rule you can always try "grunt create-rule" from the command line :)

**Comment by noxan** [comment]
Didn't know about this, sorry. Guess was just a bad timing of mine to look it up on exactly the wrong time. Maybe some hint somewhere would make it more clear.

Not sure if it is just caching or did the readme on npm not update? Can hardly imagine how this should happen otherwise. Anyhow no big deal for me, thanks for the quick response and the release is available. I'm happy ;)

**Comment by HamletDRC** [comment]
I am not actually an administrator on the npm package, so I prepare the release and then send a message to the admins asking for a deploy. I am in Central Europe and they are in Washington state in the USA... so it sometimes takes 12 hours or longer to get the deploy. I should just wait to update the README until I know it is actually deployed!
