### ISSUE TITLE
react-tsx-curly-spacing bug with comments

### ISSUE THREAD

**Issue by testerez** [Microsoft/tslint-microsoft-contrib#353]
With setting: `"react-tsx-curly-spacing": [true, "never", {"allowMultiline": true}],`
I get an error for: `<div>{/* comment */}</div>`
Error: There should be no space before '}' (react-tsx-curly-spacing)

**Comment by JoshuaKGoldberg** [comment]
#533 should fix this bug. If there's still an issue with comments, that would be a separate and unfortunately more difficult issue.
