### ISSUE TITLE
gruntfile and tsconfig are inconsistent

### ISSUE THREAD

**Issue by bgold09** [Microsoft/tslint-microsoft-contrib#360]
The grunt task for compiling the TypeScript source and the tsconfig.json in this repo do not match; clearly the config defined for grunt is the one being used in CI builds. I'd propose we keep configurations inside tsconfig.json where most people expect to find the compiler options, and let the grunt task use this file. That way, compilation is consistent regardless of whether using grunt of tsc directly. The tsconfig.json also is how VS Code finds the options to use and I'm not sure it can integrate with grunt in that way.

@HamletDRC what would you prefer?

**Comment by HamletDRC** [comment]
Sounds good to me, I think making tsconfig the single source of Truth is
the best way to go. To be honest, I don't use VS Code, so I just accepted
that file as IDE config in a pull request.
