### ISSUE TITLE
remove no-sparse-arrays rule

### ISSUE THREAD

**Issue by chrismbarr** [Microsoft/tslint-microsoft-contrib#364]
TSLint 5.1.0 was just released and it contains the `no-sparse-arrays` rule, so the rule by the same name in this project can be safely removed when support for TSLint 5.x is released.

http://palantir.github.io/tslint/rules/no-sparse-arrays

**Comment by bgold09** [comment]
FYI, I'm addressing this as part of #354

**Comment by HamletDRC** [comment]
The title said deprecate, but the git push did a remove. 
We need to remove it and it is a major release... so we'll remove it.
