### ISSUE TITLE
Remove deprecated rule 'no-unused-imports'

### ISSUE THREAD

**Issue by HamletDRC** [Microsoft/tslint-microsoft-contrib#368]
this rule is deprecated and we don't want to port it to tslint 5

**Comment by owlcode** [comment]
Why is that we want to have no-unused-imports and no-unused-variables together?

**Comment by HamletDRC** [comment]
The no-unused-variables used to not find unused imports. So we wrote our own no-unused-imports a long time ago. But now tslint fixed their rule to find unused imports (as well as the tsc compiler). So this rule can be removed.
