### ISSUE TITLE
Peer dependency issue with tslint-microsoft-contrib@5.0.0

### ISSUE THREAD

**Issue by emmanuelbuah** [Microsoft/tslint-microsoft-contrib#373]
Run into the warning below in relation to peer dependency mismatch 

`warning "tslint-microsoft-contrib@5.0.0" has incorrect peer dependency "tsutils@1.6.0".` 

Might be worth upgrading tsutils to the latest version if possible.

**Comment by Delagen** [comment]
I think this must be moved to dependencies. Because when using npm 3 with legacy bundling this throw error with module not found

**Comment by Delagen** [comment]
Any news?

**Comment by reduckted** [comment]
#371 relaxed the peer dependency to be 1.6.0 or greater. It doesn't look like it's made it into a release yet.

**Comment by HamletDRC** [comment]
Yes this is fixed a while ago. I can put it on the release branch over the
weekend.

**Comment by thomas-darling** [comment]
Sounds good - do you know when that will be released?

**Comment by HamletDRC** [comment]
Closing this as a duplicate of #371 and triggering the release today.
