### ISSUE TITLE
Rule request: mocha-avoid-skip

### ISSUE THREAD

**Issue by jesskelsall** [microsoft/tslint-microsoft-contrib#380]
Pretty straightforward, disallow use of Mocha's [`.skip()`](https://mochajs.org/#inclusive-tests) method on tests.

Like with `mocha-avoid-only`, its benefit would be to stop temporary code making it into a build, preventing tests from being ran.

I'd imagine this isn't too different to `mocha-avoid-only` to implement.

**Comment by JoshuaKGoldberg** [comment]
Indeed, very similar to the existing `mocha-avoid-only` rule and a great idea for the same reasons. It would be easiest IMO to add to that rule and rename it to something more generic (it's also valid for other test runners with the same variable names).

Perhaps `test-restriction-methods`? `test-restrictors`? 😕

**Comment by reduckted** [comment]
Just linking #455 here since you mentioned it could be generalized.

**Comment by JoshuaKGoldberg** [comment]
☠️  *It's time!* ☠️ 

Per #876, this repository is no longer accepting feature pull requests. TSLint is being deprecated and we recommend you switch to https://typescript-eslint.io.

Thanks for open sourcing with us, everyone!
