### ISSUE TITLE
Tweak `react-a11y-anchors` to ignore `href="#"` if `onClick` is present

### ISSUE THREAD

**Issue by cdeutsch** [microsoft/tslint-microsoft-contrib#383]
I don't think this part of `react-a11y-anchors` is a valid rule...

> `Enforce an anchor element's href prop value is not just #
http://webaim.org/techniques/hypertext/#keyboard

...at least not if `onClick` is present

From the article...

```html
<a href="#" onmouseover="dropdownmenu()">Products</a>
```

> Both keyboard users and mouse users will experience nothing at all when attempting to activate the link.

If `onmouseover` was `onclick` then this statement is false because the click **would** do something.

Using `<a href="#" onClick="foo()">` to trigger Javascript onClick is a very common pattern.

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is deprecated** and no longer accepting pull requests other than security fixes. See #876. ☠️ 
We recommend you instead use **[typescript-eslint](https://typescript-eslint.io)** to lint your TypeScript code with **ESLint**. ✅

👋 It was a pleasure open sourcing with you!
