### ISSUE TITLE
Cyclomatic complexity rule is turned off

### ISSUE THREAD

**Issue by bertolo1988** [Microsoft/tslint-microsoft-contrib#397]
I noticed that you are using `"cyclomatic-complexity": false`. Was it a mistake? Why aren't you using it?

**Comment by HamletDRC** [comment]
No, there is no good reason to have this turned off. 
The rule was released a lot more recently than our project... so if there are errors then we probably would not take the time to fix it. 

In general, I would turn this rule on.

**Comment by bertolo1988** [comment]
I would really like to have a proper open-source driven and well maintained tslint configuration from Microsoft since there aren't much good ones available.

If you can't handle the fixes right now, maybe you could fork it. Guys like me would really appreciate following your "recommendation".

I would gladly contribute as well.
