### ISSUE TITLE
Disallow object literal casting

### ISSUE THREAD

**Issue by megamindbrian** [Microsoft/tslint-microsoft-contrib#398]
I've fallen for a trap that could probably be avoided with linting.

Basically, if I initialize an object, then cast it, those methods aren't transferrable.
```
export class MyClass {
    someProperty: string;
    someMethod() {
    }
    constructor() {
    }
}

const literalObj: MyClass = {
    someProperty: 'this all works fine'
}

// this part fails
literalObj.someMethod();

```

All the types compile just fine, but you can see the IDE would get tripped up and not tell you that literalObj was not initialized via ``` new MyClass() ``` and therefore someMethod() is not available on that object.

One possible solution would be if the constructor is explicitly defined, it should fail to compile as the constructor would never get called on this cast.

Any suggestions?

**Comment by HamletDRC** [comment]
This is a compiler error in TypeScript 2.6. So I think you just need to upgrade to the newest version and it will help you out.
