### ISSUE TITLE
Issues with intentional backslashes in the no-octal-literal rule.

### ISSUE THREAD

**Issue by iclanton** [Microsoft/tslint-microsoft-contrib#413]
I've noticed that the no-octal-literal rule flags strings with intentionally escaped backslashes (i.e. - `"\\1"` -> \1) get incorrectly flagged by the no-octal-literal rule.

I put together a fix: https://github.com/Microsoft/tslint-microsoft-contrib/pull/412

**Comment by HamletDRC** [comment]
closed with #412
