### ISSUE TITLE
no-typeof-undefined should exclude globally declared variables like window

### ISSUE THREAD

**Issue by ian-craig** [microsoft/tslint-microsoft-contrib#415]
### Bug Report

- __TSLint version__: 5.8.0
- __TypeScript version__: 2.7.0
- __Running TSLint via__: VSCode

#### TypeScript code being linted

```ts
declare var window: any;

if (typeof window !== "undefined") {
    // do something 
}
```

with `tslint.json` configuration:

```json
{
    "rules": {
        "no-typeof-undefined": true,
    },
}
```

#### Actual behavior
TSLint gives error

```ts
[tslint] Avoid typeof x === 'undefined' comparisons. Prefer x == undefined or x === undefined: typeof window !== "undefined" (no-typeof-undefined)
```

The suggested fix would be:

```ts
if (window !== undefined) {
    // do something 
}
```

which results in `ReferenceError: 'window' is undefined at...`

#### Expected behavior

Ignore `typeof foo !== "undefiend"` when `foo` has been `declare`d globally.

**Comment by estaub** [comment]
A linter for the OPPOSITE of this rule would be useful for globals!

This is a common test in code that may run in a browser or under node.js, like server-side-rendered code.

**Comment by HamletDRC** [comment]
Does any object other than 'window' display this error?

**Comment by HamletDRC** [comment]
i.e.  why should we change this rule for *all globals* instead of just window?

**Comment by estaub** [comment]
@HamletDRC I'm misunderstanding, I suspect.  AFAICT, this has nothing to do specifically with `window`, and happens when testing for the presence of any global.  `window` is just the most common case, because it's frequently tested for to determine whether we're running in a browser.

It's very easy to imagine analogous cases, though I confess I have no recent real-world one at hand.  I think testing for some browser plugins used to sometimes use this, but global namespace pollution concerns made it now rare or extinct.

**Comment by ian-craig** [comment]
Testing `window` in code which also runs in server side rendering is a common case I've hit. I can imagine the same would apply when conditionally adding a polyfill only when the browser does not already have support.

```ts
declare var fetch: any;

if (typeof fetch === "undefined") {
    // Insert some polyfill
}
```

**Comment by HamletDRC** [comment]
OK, I did not know that server side JavaScript would throw an exception if you referenced an undefined global variable.

**Comment by estaub** [comment]
@HamletDRC,  In your browser dev tools, open a console and type
```
dfsdfdsfsdfgsdfberg
```
and press enter - you'll see that it's the same there.   Be sure to spell it right ;-)

**Comment by HamletDRC** [comment]
OK, I had no idea. 

I wonder if there is an easy way to determine if something is global or not.

**Comment by estaub** [comment]
@HamletDRC That's easy!  If you don't know where it came from, it's global.  
In other words, if there's no defining import, const, var, function, etc. in the module, then it's global by process of elimination.

**Comment by estaub** [comment]
Sorry, my last comment was thinking from a Javascript perspective, which may not be relevant, since the dev provided a declaration somewhere, e.g.  `declare var window: any;`.

In the case of a global, there's no javascript backing the declaration, but I expect that you have no way of detecting that.

**Comment by estaub** [comment]
I'm not sure, but I think something is global iff it is declared (using `declare`) outside of a namespace, and is not exported.  Don't trust this, though; it needs verification from someone with more Typescript savvy.

If any Typescript mavens see this, please confirm or deny.

**Comment by estaub** [comment]
@bradleyayers    
See issue https://github.com/Microsoft/tslint-microsoft-contrib/issues/139: it's "simpler".
I wonder if it was driven by some external authority.

Related: https://stackoverflow.com/questions/3390396/how-to-check-for-undefined-in-javascript

Could be wrong, but I believe the cases where, _in Typescript_, `x === undefined` can throw a ReferenceError (without a compiler error) are pretty limited, maybe even limited strictly to the declared-but-not-defined-global case discussed above.  So I'm happy to use it everywhere else.

**Comment by bradleyayers** [comment]
@estaub thanks for the link! I've written up a quick proposal for a new TypeScript feature related to this https://github.com/Microsoft/TypeScript/issues/23602.

**Comment by JoshuaKGoldberg** [comment]
Adding a `missing` or so as per the TS feature proposal would be great and absolutely solve the problem discussed here. 

That will almost certainly take a very long time. Until then, accepting PRs to add here.

**Comment by JoshuaKGoldberg** [comment]
Adding a `missing` or so as per the TS feature proposal would be great and absolutely solve the problem discussed here. 

That will almost certainly take a very long time. Until then, accepting PRs to add here.

**Comment by JoshuaKGoldberg** [comment]
Adding a `missing` or so as per the TS feature proposal would be great and absolutely solve the problem discussed here. 

That will almost certainly take a very long time. Until then, accepting PRs to add here.

**Comment by JoshuaKGoldberg** [comment]
☠️  *It's time!* ☠️ 

Per #876, this repository is no longer accepting feature pull requests. TSLint is being deprecated and we recommend you switch to https://typescript-eslint.io.

Thanks for open sourcing with us, everyone!
