### ISSUE TITLE
No implicit dependencies warning for devDependencies

### ISSUE THREAD

**Issue by weeco** [Microsoft/tslint-microsoft-contrib#419]
I am wondering why you disallow developers to import libraries which are listed as devDependency. Is there a specific reason for this strict rule?

For instance: Why do I need to add mocha as regular dependency instead of a devDependency in my package.json?

**Note:** I am aware I can adapt this rule with `"no-implicit-dependencies": [true, "dev"]`, but I am curious if there is a good reason to follow your guidelines which usually make sense to me.

**Comment by HamletDRC** [comment]
@weeco  My build pipeline only deploys the .js libraries that are in dependencies, and not the devDependencies section. So, if someone imports a devDependency from a production file then we get a runtime error after the deployment, which is bad. 

What we do is turn this rule on when linting production files, and turn this rule off when linting test files.
