### ISSUE TITLE
Rule request: preferred-package-imports

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/tslint-microsoft-contrib#422]
Name proposal could probably be improved for such an unusual rule...

When there are two modules that declare variables with the same name, it's easy to mistakenly import from the wrong package:

```typescript
import { action } from "mobx"; // this one?
import { action } from "mobx-safe"; // or this one?
```

A rule that lets projects map imports to their preferred package imports would help:

```json
{
    "rules": {
        "preferred-package-imports": {
            "mobx-safe": {
                "action": {
                    "override": ["*"],
                    "reason": ["Technical mumbo jumbo..."]
                }
            }
        }
    }
}
```

Bonus points if this rule comes with an auto-fixer!

**Comment by HamletDRC** [comment]
@JoshuaKGoldberg Your IDE is picking the wrong import, right? 
It sounds like maybe we should try to extend this existing rule: https://palantir.github.io/tslint/rules/import-blacklist/

**Comment by JoshuaKGoldberg** [comment]
I can try posting there!

**Comment by JoshuaKGoldberg** [comment]
https://github.com/Microsoft/tslint-microsoft-contrib/issues/415
