### ISSUE TITLE
[Feature Request] `import-name` support snake_case file names

### ISSUE THREAD

**Issue by dosentmatter** [Microsoft/tslint-microsoft-contrib#424]
https://github.com/Microsoft/tslint-microsoft-contrib/blob/master/src/importNameRule.ts#L101

The current code allows periods, `.`, and hyphens, `-`, in file name imports and converts them to camelCase. Is it possible to allow underscores, `_`, as well?

I know underscores for file names isn't as common in javascript/typescript but I see it used sometimes. Currently, tslint would suggest `import snake_case from 'snake_case';` and I think snake_case for variable naming is less common.

**Comment by JoshuaKGoldberg** [comment]
+1, this should be done. Seems like a nice and straightforward fix.
