### ISSUE TITLE
Why no-inner-html rule (noInnerHtmlRule) is marked as typescriptOnly?

### ISSUE THREAD

**Issue by schubar-tibco** [Microsoft/tslint-microsoft-contrib#426]
Hi, I'm wondering why most of the rules and noInnerHtmlRule specifically are not available for JavaScript. Is this because of some technical issue (e.g. incompatible AST, API or missing utils) or is that the policy of the company?

**Comment by JoshuaKGoldberg** [comment]
Hi @schubar-tibco! In short, we can't get full type intelligence without a `tsconfig.json`. 

Rules that are marked as typescriptOnly are ones that require use of TypeScript's compiler program APIs to inspect static types, which requires the existence of a TypeScript project. See https://palantir.github.io/tslint/usage/type-checking/ for a bit more info. 

It's certainly not a policy of the company, we'd very much like to have these be as easy as possible 😊.
