### ISSUE TITLE
New rule: Accessibility rule around emoji

### ISSUE THREAD

**Issue by astorije** [microsoft/tslint-microsoft-contrib#432]
It's very easy to make emoji inaccessible and @LJWatson wrote a very nice and short article about it: https://tink.uk/accessible-emoji/

`eslint-plugin-jsx-a11y` has a rule for this that we could emulate: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/accessible-emoji.md

**Comment by JoshuaKGoldberg** [comment]
_(changing difficulty from Medium to Easy because the source rule is relatively simple... and I love emojis)_

**Comment by digilou** [comment]
Hi! I'd love to give this a shot for Hacktoberfest and improve accessibility on the web.

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated**; therefore, it and tslint-microsoft-contrib are no longer accepting pull requests for major new changes or features. See #4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint or tslint-microsoft-contrib locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
