### ISSUE TITLE
react-this-binding-issue should ignore ref callbacks

### ISSUE THREAD

**Issue by dgoldstein0** [microsoft/tslint-microsoft-contrib#438]
In a react render function, react-this-binding-issue fires on `ref` when it should not.  E.g.:

```
class Form extends React.Component<{action: string}, {}> {
  render() {
    return (
      <form
         ref={f => (this.form = f)} // lint error here
         action={this.props.action}
         >
         {this.props.children}
      </form>
    );
  }
}
```

**Comment by cpsubrian** [comment]
Probably also common "render props" like `render={() => <MyComponent />}` (or at least a way to white-list)

**Comment by hasparus** [comment]
@cpsubrian Isn't this still a problem in render props though?
It will cause redundant function allocation and rerender in PureComponents.

However a whitelist would be really nice.
Maybe even with default value `["ref"]`, because of (https://github.com/palantir/tslint-react/pull/107)

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated**; therefore, it and tslint-microsoft-contrib are no longer accepting pull requests for major new changes or features. See #4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint or tslint-microsoft-contrib locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
