### ISSUE TITLE
Allow this.timeout in mocha-no-side-effect-code

### ISSUE THREAD

**Issue by astorije** [Microsoft/tslint-microsoft-contrib#446]
`this.timeout()` is [valid at suite-level](https://mochajs.org/#suite-level) but by default, `mocha-no-side-effect-code` says:

```
ERROR: 28:3  mocha-no-side-effect-code  Mocha test contains dangerous variable initialization. Move to before()/beforeEach(): this.timeout(5000)
```

At the moment, we have to ignore it using the following, but it would be nice if the rule was whitelisting it itself:

```yaml
mocha-no-side-effect-code:
  - true
  - ignore: 'this\.timeout'
```

According to the docs, it seems [`this.retries()`](https://mochajs.org/#retry-tests) and [`this.slow()`](https://mochajs.org/#test-duration) should get the same preferential treatment.

**Comment by JoshuaKGoldberg** [comment]
Sounds like there should be a whitelist as a config setting!

**Comment by astorije** [comment]
That's what `ignore` is for, no?
My suggestion here was to ignore `this.timeout`, `this.retries`, and `this.slow` as these are allowed by Mocha itself. What do you think about this?

**Comment by JoshuaKGoldberg** [comment]
Ah, you're right! I missed that the rule has that as a config setting. Thanks 😁

It should be easy to add a default `ignore` value to the rule that's a regex containing those values.

**Comment by astorije** [comment]
Where would you add this? In the recommended preset, or in the code?

**Comment by astorije** [comment]
@JoshuaKGoldberg, I gave it a shot in #453!
