### ISSUE TITLE
Genericize error messages in noInnerHtmlRule.ts

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/tslint-microsoft-contrib#458]
The `no-inner-html-rule` rule _used_ to be limited to jQuery, but was made more generic (#425) to work with projects not using jQuery. Without changing any more behavior, it'd be good to fix the rule's strings:

* Change `FAILURE_JQUERY`'s `html()` complaint text to specifically mention whichever invalid function is being flagged.
* Replace "`JQUERY`" in the source code with some more generic word. "`RAW_HTML`"?

**Comment by mateoholman** [comment]
Hi, I'll tackle this issue for Hacktoberfest if no one is curently working on it?

**Comment by JoshuaKGoldberg** [comment]
Great!

**Comment by mesaugat** [comment]
@JoshuaKGoldberg This issue needs to be closed because it has been already done in #428

**Comment by JoshuaKGoldberg** [comment]
Ah, thanks for the catch. Closed.
