### ISSUE TITLE
Recommended max-func-body-length rule ignores functions named /.+describe.+/ as well

### ISSUE THREAD

**Issue by makotom** [Microsoft/tslint-microsoft-contrib#465]
# Repro
[I've prepared a easy-to-start test case](https://github.com/makotom/tslint-test-20180719). Clone the package, run `npm i`, and then `npm run lint`.

**OR**

1. Write a TypeScript code in which `xyzdescribexyz` is called with a 101-line arrow function as a parameter.
2. Run tslint with "tslint-microsoft-contrib" rules.

## Expected result
"Max arrow function body length exceeded" error should be raised at the point calling `xyzdescribexyz`.

## Actual result
No error for `xyzdescribexyz`.
Note that the test case I provided also includes a test for `describ`, to which an error is raised as expected.

# Considerations
This happens because [the current recommended options for max-func-body-length rule sets "ignore-parameters-to-function-regex" to "describe"](https://github.com/Microsoft/tslint-microsoft-contrib/blob/master/recommended_ruleset.js#L122). Therefore, functions whose name matches /.+describe.+/ (I mean not only /^describe$/) will be ignored for this rule by default.

I recognize that this option is set not to raise errors for describe() in Mocha (indeed it is stated that "this can be useful for Mocha users to ignore the describe() function" in README), and I personally think the intention itself is rational. However, since the given rule matches functions other than describe(), which is not a good idea, I would propose to change the recommended value to a stricter one, such as /^describe$/.

**Comment by JoshuaKGoldberg** [comment]
Hi @makotom - thanks for such a detailed issue! The problem and solution as you've stated them seem reasonable. I'd love to see a pull request adding them in!

**Comment by makotom** [comment]
@JoshuaKGoldberg, thank you for your prompt response!

[I'm preparing a pull request](https://github.com/makotom/tslint-microsoft-contrib/commit/049b82b81c2a65e6073ab7f7b7376a8e4d50f292), but since I found another issue #468 and it needs [this insane hack](https://github.com/makotom/tslint-microsoft-contrib/blob/049b82b81c2a65e6073ab7f7b7376a8e4d50f292/src/tests/MaxFuncBodyLengthRuleTests.ts#L290), I am suspending to post a PR.
Once #468 has got fixed, or if the test is unrequired, I would like to go with PR. :)
