### ISSUE TITLE
New rule: chai-prefer-deep-equal

### ISSUE THREAD

**Issue by Nebulis** [microsoft/tslint-microsoft-contrib#473]
Even though there are some use cases for `.eql`, `deep.equal` can be used in its place most of the time as well. 

The main issue with `eql` is that it's not meaningful. Without reading the documentation it is not clear that it's doing a deep comparison.

Throw `eq`, `eqs` and `equal` into the mix, then you often get questions about the differences between all the assertions.

The idea of this rule is to favor `deep.equal` usage over `eql` and `eqls`.
The rule can eventually go further by favoring equal over `eq` and `eqs`.

Tell me what you think about it ?

**Comment by JoshuaKGoldberg** [comment]
I like this very much!

There are likely many instances where this would be the case: you've mentioned several already just for Chai. How about a more generic name, like `no-unclear-assertions` or `clear-test-assertions`?

**Comment by zephinzer** [comment]
this is needed!

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated**; therefore, it and tslint-microsoft-contrib are no longer accepting pull requests for major new changes or features. See #4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint or tslint-microsoft-contrib locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
