### ISSUE TITLE
Rule request: prefer either forEach or forOf

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/tslint-microsoft-contrib#474]
For most modern environments, it's likely slightly preferable to use `for-of` instead of `forEach` when the body of the loop is an arrow function or function expression:

```typescript
mySet.forEach((value) => { /* ... */ });
```

```typescript
for (const value of mySet) { /* ... */ }
```

On the other hand, IE 11 doesn't generally support `for-of` with some output types of TypeScript, so it might be necessary to only use `forEach`. Lovely.

It'd be useful to have a rule that takes in a preference (presumably `for-of` by default) and complains when that isn't adhered to.

**Comment by nicojs** [comment]
Why would `for-of` be slightly preferable? Is it because it defers executions when working with iterables? Or are there other benefits?

**Comment by JoshuaKGoldberg** [comment]
Indeed! 

```typescript
for (const await value of getMyAsyncIterableValues()) {
    if (value.status === "last") {
        break;
    }
}
```

**Comment by JoshuaKGoldberg** [comment]
> if there's a `break` or `return`

Interesting. TypeScript will complain if there's a `break` in the function, and I don't know if there are many cases where we could detect that a `continue`/`break`/`return` is doing what the author intended one of the other statements to be.

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated**; therefore, it and tslint-microsoft-contrib are no longer accepting pull requests for major new changes or features. See #4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint or tslint-microsoft-contrib locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
