### ISSUE TITLE
Typescript v3 compatibility

### ISSUE THREAD

**Issue by zerkms** [Microsoft/tslint-microsoft-contrib#475]
A new shiny typescript v3 was released today

This issue is here to track the `tslint-microsoft-contrib` compatibility with it

**Comment by ben8p** [comment]
Looking forward for a release (at least a patch release).
Because that prevents us from upgrading to typescript 3 (or we loose many rules...)

**Comment by JoshuaKGoldberg** [comment]
After testing a bit, it looks like #478 should have resolved any issues here. Will release a `5.1.1` patch version now!
