### ISSUE TITLE
Replace Grunt dependency with npm scripts

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/tslint-microsoft-contrib#484]
Grunt is a bit hefty as a dependency. It'd be nice to move away from it and have simpler `npm run *` scripts instead.

**Comment by IllusionMH** [comment]
I can take on this next week if you don't mind accept PR on this. I have understanding how to migrate common functionality, however I'll need some help to understand how better migrate all custom tasks.

**Comment by JoshuaKGoldberg** [comment]
Sure, that'd be great! #489 might be a good first step to do as part of this one.

**Comment by IllusionMH** [comment]
I have first working iteration on this. My initial goal was to achieve same output and errors if any as Grunt tasks. 
CLI tools are used for regular tasks - clean, TypeScript compile, copy, lint, tests. For custom tasks (except creating new rule) I've created separate JS files based on grunt tasks with only minor changes.

@JoshuaKGoldberg I have a lot of questions about details. Is it possible to chat somewhere (it might be faster) or discuss everything here in PR?

**Comment by JoshuaKGoldberg** [comment]
Sure! Shoot me an email at jogol@microsoft.com and we can work out something more realtime. That'd be wonderful.
