### ISSUE TITLE
Enable more TSLint rules from core

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/tslint-microsoft-contrib#491]
Keeping a pending list on this issue of rules that would be nice to enable internally for tslint-microsoft-contrib. For each rule, it'd be great to see a single PR that enables it in `tslint.json` and fixes any resultant failures in source code.

 - [x] ban-types
 - [ ] deprecation
 - [ ] jsdoc-format
 - [ ] member-access
 - [x] no-any
 - [ ] no-boolean-literal-compare
 - [ ] no-inferrable-types 
 - [ ] no-internal-module / no-namespace
 - [x] no-non-null-assertion
 - [ ] no-unbound-method
 - [ ] no-unsafe-any
 - [ ] prefer-for-of
 - [ ] prefer-function-over-method
 - [x] prefer-readonly
 - [ ] restrict-plus-operands
 - [ ] strict-boolean-expressions
 - [ ] strict-type-predicates

**Comment by reduckted** [comment]
It looks like the current grunt task doesn't specify the TypeScript project, which means no type-checked rules are used. There are three warnings that pop up:

```
Running "tslint:prod" (tslint) task
Warning: The 'no-cookies' rule requires type information.
Warning: The 'no-use-before-declare' rule requires type information.
Warning: The 'prefer-readonly' rule requires type information.
```

If you run with type checking, the 'no-use-before-declare' and 'prefer-readonly' rules produce quite a lot of violations.

**Comment by JoshuaKGoldberg** [comment]
Hmm, that was probably set up before TSLint even had type checking. +1.

**Comment by reduckted** [comment]
It also looks like the grunt task isn't linting everything that it could. The `no-null-keyword` rule has been turned on, and running `npm test` results in everything passing, but if you run tslint directly, there are a handful of cases where the `no-null-keyword` rule finds problems. In any case, those instances of using null have been fixed indirectly by #570, and the linting via grunt will no doubt end up being fixed in #484.

**Comment by reduckted** [comment]
@JoshuaKGoldberg, not sure if you want to track it here as well, but I've just disabled `no-use-before-declare` (tracked at #603) as a result of turning on type-checking in #604.

**Comment by JoshuaKGoldberg** [comment]
Awesome, yes please! I'll add them to the list.

**Comment by JoshuaKGoldberg** [comment]
Now that the tooling is a bit more fleshed out, marking this as a good first issue and easy difficulty. Updating the OP to be a bit more clear.

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated**; therefore, it and tslint-microsoft-contrib are no longer accepting pull requests for major new changes or features. See https://github.com/palantir/tslint/issues/4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint or tslint-microsoft-contrib locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
