### ISSUE TITLE
function-name: add private static method regex

### ISSUE THREAD

**Issue by ckhatri** [Microsoft/tslint-microsoft-contrib#498]
If you have a private static method, currently I believe the linter reads it as private first and then uses the private regex. But I believe it should still use the static regex, since its a static method and its a great way to show that it is. 

so private static methods currently are linted to be: getPotatoes() instead of GET_POTATOES().

Was wondering if y'all agree.

**Comment by JoshuaKGoldberg** [comment]
Great catch, thanks for posting this! This feels like something that should be configurable. Relevant options:
* Validate private statics as privates
* Validate private statics as statics
* Validate private statics as both both privates and statics

Thoughts?
