### ISSUE TITLE
Use (j|t)sx in getLanguageVariant, rather than just tsx

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/tslint-microsoft-contrib#527]
...and of course, immediately after #525 was resolved, I remembered that we haven't updated for TypeScript being able to run on `.jsx` files as well as `.tsx`.

**Comment by dnguneratne** [comment]
Can I work on this?

**Comment by JoshuaKGoldberg** [comment]
Absolutely @dnguneratne, please do! It should be a quick change to the regular expression mentioned in that issue.

**Comment by dnguneratne** [comment]
I think I need a bit of clarity here. 
In PR #525,

-- `src/utils/AstUtils.ts` --
`if (/.*\.tsx/i.test(node.fileName)) {` was replaced with 
`if (node.fileName.endsWith('.tsx')) {`.

If I am understanding this one correctly I should change
`if (node.fileName.endsWith('.tsx')) {` to
`if (node.fileName.endsWith('.(j|t)sx')) {` right?

**Comment by JoshuaKGoldberg** [comment]
Hey @dnguneratne - looks like this was already resolved. All is well!

By `(j|t)` I was referring to regular expression syntax implying it could be satisfied by `.jsx` or `.tsx` at the end.

**Comment by dnguneratne** [comment]
Got it. Thanks for the clarification.
