### ISSUE TITLE
Tracking for a post-Hacktoberfest version: 6.0

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/tslint-microsoft-contrib#585]
There have been a _lot_ of great PRs sent in during October _(and more to come!)_. ✨ 

Quite a few of these are breaking, such as marking rules or formatters as deprecated (#504, #563, #580, etc.). I think it makes sense to change any mentions of the next version from 5.2.2 to 6.0.0. This would be more accurate in representing how major some of the repository changes are and more reflective of the great community work that happened this month.

_(Continues comment at https://github.com/Microsoft/tslint-microsoft-contrib/issues/459#issuecomment-433093617.)_

**Comment by joelalejandro** [comment]
Agreed on considering the next version as a major release. 🌈

**Comment by IllusionMH** [comment]
Look like it should be major release because `src/utils/ErrorTolerantWalker.ts` was removed while it was available in npm package.
Other changes at least linked in OP don't require major version change (deprecation warnings should be ok for minor. Please correct me if I'm wrong).

**Comment by JoshuaKGoldberg** [comment]
Planning on doing this within the next two days. 🎉

**Comment by JoshuaKGoldberg** [comment]
https://www.npmjs.com/package/tslint-microsoft-contrib/v/6.0.0-beta is available now! Release notes are up at https://github.com/Microsoft/tslint-microsoft-contrib/wiki/Release-Notes, minutes notes on what's breaking - will add those today.

/cc @IllusionMH @joelalejandro @mesaugat

**Comment by joelalejandro** [comment]
Awesome news! I've reached to the maintainer of `tslint-airbnb-config` to propose an update there as well. Thanks @JoshuaKGoldberg :D

**Comment by JoshuaKGoldberg** [comment]
https://www.npmjs.com/package/tslint-microsoft-contrib/v/6.0.0 is released. Closing this issue and opening a new one for tracking 7.0. Thanks folks!
