### ISSUE TITLE
Enable no-use-before-declare in source code

### ISSUE THREAD

**Issue by reduckted** [Microsoft/tslint-microsoft-contrib#603]
The `no-use-before-declare` was temporarily disabled as part of #567. It needs to be re-enabled.

**Comment by reduckted** [comment]
Most of the lint errors caused by this rule would be fixed once #586 is fixed, because the majority are caused by the `RuleWalker` class being declared after the `Rule` class.

**Comment by JoshuaKGoldberg** [comment]
Hey, sorry to shut this down, but I think we can skip having the rule enabled. Per the [docs](https://palantir.github.io/tslint/rules/no-use-before-declare/):

> This rule is primarily useful when using the var keyword since the compiler will automatically detect if a block-scoped let and const variable is used before declaration. Since most modern TypeScript doesn’t use var, this rule is generally discouraged and is kept around for legacy purposes. It is slow to compute, is not enabled in the built-in configuration presets, and should not be used to inform TSLint design decisions.

Thoughts?

**Comment by reduckted** [comment]
> Thoughts?

Sounds good to me. All of the errors seemed to be around classes being "used" before they were defined (which wasn't technically the case), and by the sounds of it, the rule is targeted more at variables than classes.
