### ISSUE TITLE
Extend tslint.json from tslint:all

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/tslint-microsoft-contrib#608]
This will require disabling a bunch of rules, many of which will be listed in #491. Our `tslint.json` predates the ability to extend configurations.

**Comment by IllusionMH** [comment]
Can I ask why `tslint:all` instead of `tslint:recommended`?

**Comment by JoshuaKGoldberg** [comment]
I personally prefer `tslint:all` for a really strict set of rules to catch as much as possible. In my experience, the recommended ruleset is a good ramping up point for folks less familiar with linting, but the full ruleset (with some key annoying rules disabled) catches quite a few things the recommended one does not.

For example, out of the out-of-the-box configs, only `tslint:all` has `strict-boolean-expressions`, `no-floating-promises`, and `no-for-in-array`.

**Comment by IllusionMH** [comment]
That are interesting points. Thanks!
