### ISSUE TITLE
Remove SDL hooks metadata and build steps

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/tslint-microsoft-contrib#611]
SDL refers to the [Microsoft Security Development Lifecycle](https://www.microsoft.com/en-us/sdl). It's a bit of extra work to add our own metadata on top of TSLint's. Does anybody use this?

/cc @HamletDRC

**Comment by HamletDRC** [comment]
@JoshuaKGoldberg honestly no, we can stop updating this. MS kept a list of warnings in Warnings Central that we updated. But we can kill this.

**Comment by JoshuaKGoldberg** [comment]
☠️  *It's time!* ☠️ 

Per #876, this repository is no longer accepting feature pull requests. TSLint is being deprecated and we recommend you switch to https://typescript-eslint.io.

Thanks for open sourcing with us, everyone!
