### ISSUE TITLE
Remove Appveyor

### ISSUE THREAD

**Issue by IllusionMH** [Microsoft/tslint-microsoft-contrib#613]
After #596 was merged - now Travis CI verifies on both Linux and Windows.

The question is: is there a need for two CI tools?

**Comment by JoshuaKGoldberg** [comment]
Great observation - no, and anecdotally I found Appveyor to be slower than Travis. We can _probably_ get rid of it, but I'll try to get input from @HamletDRC first.

**Comment by HamletDRC** [comment]
@JoshuaKGoldberg  sure, get rid of Appveyor.
