### ISSUE TITLE
Question: Add tslint for build-tasks folder?

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/tslint-microsoft-contrib#615]
At this moment there are no linting for  `.js` files in `build-tasks` folder, since separate `jsRules` entry should be added to config.

Do you think it make sense add `tslint.json` to `build-tasks` folder? Not shure that this should be a build step, but at leas will be helpful to have it in IDE.

For example - I've missed `"` in #612 during review.

**Comment by JoshuaKGoldberg** [comment]
Ah, yes, +1 to have linting (or at least formatting) as part of build. I personally use `"` by preference and forgot to check for it in the files 😂.

**Comment by mesaugat** [comment]
Would it be fine to use [prettier](https://prettier.io/) throughout the codebase or for the `build-tasks` folder? It has good IDE support too.

**Comment by JoshuaKGoldberg** [comment]
> prettier

Indeed: https://github.com/Microsoft/tslint-microsoft-contrib/issues/558

**Comment by IllusionMH** [comment]
I think it will be great. Although I don't know if `tslint-prettier-config` supports JS files.

**Comment by mesaugat** [comment]
Do we still need this? What JavaScript rules do we want to enable?

We can add `jsRules` key to `tslint.json` or use `eslint` for `build-tasks` folder separately with `eslint:recommended` ruleset. What are your thoughts?

**Comment by IllusionMH** [comment]
Reimplementing them in TS wouldn't help much because it will still require separate tslint.json as well as tsconfig.json. And I'm not sure what typed rules will be beneficial here. So if only goal is linting - migration won't be very helpful.

However, I don't have objections to migrate them to TS. I was thinking to implement them in TS, but it was discussed and intentionally skipped from initial implementation.
@JoshuaKGoldberg since build tasks already performing well and there are no more dependencies that are blocked by build, it makes sense to migrate them now?

**Comment by JoshuaKGoldberg** [comment]
☠️  *It's time!* ☠️ 

Per #876, this repository is no longer accepting feature pull requests. TSLint is being deprecated and we recommend you switch to https://typescript-eslint.io.

Thanks for open sourcing with us, everyone!
