### ISSUE TITLE
Enhancement: Possible improvements for watchers

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/tslint-microsoft-contrib#618]
This issue is list of suggestion that can improve development workflow related to watchers.

Done. ~`npm start` - currently requires `npm test` first.~ Easy change - perform `clean` and `copy:json` before `tsc --watch`.

**Pros:** everything will work out of the box.
**Cons:** will require few seconds more to start.

`watch:runt-tests` - performs initial test run when started (after watcher ready) and might delay test run if developer changes watched file before. To skip initial test run it is possible to add ``--skip-initial` flag (or revert logic and have  `--initial-run` to force it). 

**Pros:** "help" devs who will prefer skip initial.
**Cons:** need to parse flags (reuse same lib that TSLint uses or simple implementation as in `create-rule`)

`watch:runt-tests` - will schedule next run after current if watched file changed, which will delay feedback. It is currently blocked by `npm-run-all` issue, but if `AbortController` support will be added - add `--restart` (or `--restart-on-change`) flag that will stop active test run and start new one, that will test/lint latest files.

**Pros:** faster feedback
**Cons:** need to parse flags; needs lib update; changes might restart test before it was finished to often (but its optional flag for those who want)

This is list of possible improvements for current simple implementation.

Next improvements might be considered for future:
- **Only run tests that are related to changed files:** there is convention between rule file name, tests file name and folder in `test` (or more precise - `tslint.json` analysis). If file changes - decide what are related tests and run only small list. If no matching - run full test suite.

- **Custom integration with TS compiler API** - will help to avoid watcher for compiled `.js` files.

These two option will require to drop convenient and easy to use `runAll`, greater effort for mapping and cross-platform scrip running, but will make things noticeable faster.
Mapping will be simple after finishing #489.

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated**; therefore, it and tslint-microsoft-contrib are no longer accepting pull requests for major new changes or features. See https://github.com/palantir/tslint/issues/4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint or tslint-microsoft-contrib locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
