### ISSUE TITLE
Incorrect deprecation message for fix-no-require-imports formatter

### ISSUE THREAD

**Issue by IllusionMH** [Microsoft/tslint-microsoft-contrib#620]
`no-require-imports` is part of `tslint` repo and doesn't have fixer ([rule meta](https://github.com/palantir/tslint/blob/master/src/rules/noRequireImportsRule.ts#L25-L34)).

Therefore change in #580 should be reverted or fixer implemented in `tslint` repo.

`no-var-keyword` rule related to other deprecated formatter in #580 related to  [has fixer](https://github.com/palantir/tslint/blob/master/src/rules/noVarKeywordRule.ts#L29)

**Comment by JoshuaKGoldberg** [comment]
Good catch - I've had auto-suggestions for that in VS Code, but can't find docs for that in VS Code or TypeScript with some quick Googling. Odd.

We don't want to have the maintenance cost of these custom formatters here so +1 to reimplementing the fixer in the `tslint `repo.

**Comment by IllusionMH** [comment]
TS made it code fix in 2.8 https://github.com/Microsoft/TypeScript/pull/22204
VS Code https://code.visualstudio.com/updates/v1_22#_suggestion-code-actions-for-javascript-and-typescript

WebStrom have quick action for this, but need to check.
