### ISSUE TITLE
Enhancement: Make `no-relative-imports` rule stricter

### ISSUE THREAD

**Issue by IllusionMH** [Microsoft/tslint-microsoft-contrib#624]
At this moment `no-relative-imports` dissalows `..` only at the beginning of the import path (see #508).

Since next release most likely will be [major release](https://github.com/Microsoft/tslint-microsoft-contrib/issues/585) it is good opportunity to make "breaking" change disallow `..` inside path.

This will be easy check and won't require a lot of effort.

Ideally - disallow not only `/../` but also `/./` inside of path.

Update rule instead of new one - because it will be basically copy-paste with minor changes in check function (that shouldn't conflict with existing) and error message.

**Comment by JoshuaKGoldberg** [comment]
Sure, if this gets in within the next couple of days let's fast-track it into 6.0. On the other hand, since `no-relative-imports` is an odd and rarely used rule _(I've been recommending against it for some time now)_, if this gets in as a 6.1 change instead of 6.0.1, that feels fine too.

**Comment by JoshuaKGoldberg** [comment]
1. That seems fine. It'd be nice to keep it, but if it overly complicates the implementation details, agreed that it's not critical. We can always file a followup issue to re-add it.
2. Yes, unfortunately. Some Windows developers use `\` as path separators AFAIK.
