### ISSUE TITLE
Better describe and suggest new rules' version options

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/tslint-microsoft-contrib#648]
Following @IllusionMH's comment in https://github.com/Microsoft/tslint-microsoft-contrib/pull/647#issuecomment-436277440 -  we should have a better template for what users should put in README.md as the rules' starting version.

During the release process, we change them to what's correct, but until then it can be misleading to see incorrect version numbers in the big README.md table.

This should be a small intermediate fix until #575 gets rid of that table.

**Comment by IllusionMH** [comment]
In offline discussion `@next` was picked.
