### ISSUE TITLE
Don't recommend no-use-before-declare or other deprecated or legacy rules

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/tslint-microsoft-contrib#649]
Following discussion in https://github.com/vuejs/vue-cli/issues/2712

**Comment by IllusionMH** [comment]
Is there a clear way to determine which rules are "deprecated" or "legacy"?
For example `no-use-before-declare` doesn't have any hints (metadata properties) except couple sentences in description.

In this case - changes should be made to `additional_rule_metadata.json` but this will also affect `tslint-warnings.csv` which I'm not sure how it is used.

**Comment by JoshuaKGoldberg** [comment]
@IllusionMH that's a good idea. You could also consider filing an issue in TSLint core to add "legacy"/"discouraged" field(s) to metadata.

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is deprecated** and no longer accepting pull requests other than security fixes. See #876. ☠️ 
We recommend you instead use **[typescript-eslint](https://typescript-eslint.io)** to lint your TypeScript code with **ESLint**. ✅

👋 It was a pleasure open sourcing with you!
