### ISSUE TITLE
Mark no-reserved-keywords as deprecated

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/tslint-microsoft-contrib#652]
### Bug Report
 
-   **`tslint-microsoft-contrib` version**: 6.0.0-beta
-   **TSLint version**: 5.11
-   **TypeScript version**: 3.1.3
-   **Running TSLint via**: *

There are still issues being reported with `no-reserved-keywords` (#395, #403), but the rule is an inferior version of TSLint core's [`variable-name`](https://palantir.github.io/tslint/rules/variable-name) with `ban-keywords`, right?

If we could remove `no-reserved-keywords`, that would be great.

**Comment by astorije** [comment]
You got it!
