### ISSUE TITLE
new rule: react: className starts with file name

### ISSUE THREAD

**Issue by slawomir** [microsoft/tslint-microsoft-contrib#66]
Enforce React component's className starts with current file name.
## Example

In MyComponent.ts
### Ok

``` javascript
React.createElement("div", { className: 'MyComponent' });
React.createElement("div", { className: 'MyComponent-Icon MyComponent-Icon-hover' });
```
### Wrong

``` javascript
React.createElement("div", { className: 'panel' });
```

**Comment by JoshuaKGoldberg** [comment]
Hey @slawomir, are you still interested in taking this one? It seems like enforcing at least one of a file's React components, if there are any, have the file's name would be useful.

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated**; therefore, it and tslint-microsoft-contrib are no longer accepting pull requests for major new changes or features. See #4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint or tslint-microsoft-contrib locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
