### ISSUE TITLE
Odd whitespace characters in tslint-warnings.csv

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/tslint-microsoft-contrib#675]
See conversation in #674.

> Why there are no spaces after `.`? Like ``that `role`.Many``, `particular roles.Some `, ``to `role='link'`.A reference``.

> Change above contain spaces (to many?). Probably requires build script update.

**Comment by reduckted** [comment]
From the PR (#709):
1. `react-a11y-role-supports-aria-props` was using string concatenation in the description, but didn't have trailing spaces at the end of each string.
2. `react-a11y-role was using a template literal` with a new line and indentation in the middle.
