### ISSUE TITLE
Ease up on strictness in the default configs of naming rules

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/tslint-microsoft-contrib#678]
Splitting off from @astorije's comment in #672: `function-name` suggesting static functions be UPPERCASE is odd and nonstandard behavior. That should not be enabled as part of the default configuration.

We should also double-check other rules to see if there are odd naming conventions espoused by their defaults.

**Comment by astorije** [comment]
I'm fine with the strictness here btw, just this convention felt odd compared to what's out there.

**Comment by astorije** [comment]
Porting here a suggestion from #822: making the `allow-size-argument` option of `prefer-array-literal` to be `true` by default.

**Comment by JoshuaKGoldberg** [comment]
☠️  *It's time!* ☠️ 

Per #876, this repository is no longer accepting feature pull requests. TSLint is being deprecated and we recommend you switch to https://typescript-eslint.io.

Thanks for open sourcing with us, everyone!
