### ISSUE TITLE
Convert all existing rules to use a `walk` function instead of extending AbstractRule

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/tslint-microsoft-contrib#680]
Partner to #586: following palantir/tslint#2522, we should be recommending a ts.forEachChild strategy.

Accepting any PRs that take an existing rule and convert it to `walk`! ✨

**Comment by IllusionMH** [comment]
Reopening this issue because it tracks migration of all rules and was closed automatically with `fixes #NNN` text in PR text.

**Note to reviewers:** check if PR text strictly follows template and will close this one again.

**Comment by JoshuaKGoldberg** [comment]
Looks like this was accomplished. Thanks so much folks! 💖
