### ISSUE TITLE
Rule suggestion: void-zero

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/tslint-microsoft-contrib#693]
### Rule Suggestion

**Is your rule for a general problem or is it specific to your development style?**

One could argue for either, but IMO this is more of a general problem.

**What does your suggested rule do?**

Some projects have instances of `void 0` instead of `undefined`. They technically resolve to the same thing _(and minifiers typically convert to `void 0` to safe a few characters)_ but `void 0` can be confusing to newcomers. As a stylistic preference to make it easier for newcomers I think it'd be reasonable to have a rule to prefer `undefined`.

**List several examples where your rule could be used**

[VS Code](https://github.com/microsoft/vscode) has a lot of these.

Given:

```typescript
function takesMaybe(param1: string | undefined, param2: number) { /* ... */ }
```

Instead of:

```typescript
function takesMaybe(void 0, 7);
```

Prefer:

```typescript
function takesMaybe(undefined, 7);
```

**Additional context**

/cc @roblourens because I get a little irked every time I wade into VS Code source 😄

**Comment by roblourens** [comment]
Me too, I just replaced all of our `void 0` :)
