### ISSUE TITLE
new rule: document.domain whitelist

### ISSUE THREAD

**Issue by HamletDRC** [Microsoft/tslint-microsoft-contrib#7]
Taken from https://msdn.microsoft.com/en-us/library/cc307418.aspx

Scripts setting document.domain to any value should be validated to ensure that:
1. The site checks that the caller is on a list of allowed sites before setting document.domain.
2. If the site deals with PII in any way, document.domain is not set to a top-level domain (for example, live.com) but only to an appropriate subdomain (for example, billing.live.com).

**Comment by brndkfr** [comment]
This is a must have for Quality Essentials - would be nice to check this via the rule.

**Comment by HamletDRC** [comment]
@brndkfr I wrote this rule and will make a release.

**Comment by brndkfr** [comment]
awesome!
