### ISSUE TITLE
Unable to debug rules using the Run TSLint Tests template

### ISSUE THREAD

**Issue by noamyogev84** [Microsoft/tslint-microsoft-contrib#703]
### Bug Report

-   **`tslint-microsoft-contrib` version**: latest
-   **TSLint version**: 5.11.0
-   **TypeScript version**: 3.1.1
-   **Running TSLint via**: VSCode
-   **Node.js version**:8.12.0
-   **OS**: win10 x64

Trying to debug tests under `tests` folder with no success. 
Command: `node.exe --inspect-brk=27157 node_modules\tslint\bin\tslint --test -r dist/src tests/**` 
Output: `Debugger listening on ws://127.0.0.1:27157/da6329d9-5a8f-4729-965a-9339e2d17953`

Debug console lists all tests with `passed`, no breakpoint is being hit.

**Comment by reduckted** [comment]
How are you running that command? Selecting the _"Run TSLint Tests"_ debugging configuration in VS Code and starting debugging works fine for me. Here's the steps I took:

![debug](https://user-images.githubusercontent.com/10321525/50534016-a0ebb780-0b81-11e9-8555-b80250af6273.gif)

**Comment by noamyogev84** [comment]
Hi @reduckted , exactly as you describe.
No breakpoint is being hit in my rule though.

Can you share the test folder content that's associated with the test your'e showing?

Thanks 🏆

**Comment by IllusionMH** [comment]
I was able to reproduce this issue.
In my case it may work for some lines, and doesn't work for other.

For example I tried to place 3 breakpoints in [`src/validTypeofRule.ts`](https://github.com/Microsoft/tslint-microsoft-contrib/blob/051974247f7a8cd8f3be133478acd2a81ba4d1bf/src/validTypeofRule.ts#L29-L36)
```ts
public apply(sourceFile: ts.SourceFile): Lint.RuleFailure[] {
    if (Rule.isWarningShown === false) { // <- Doesn't work (never hit).
        console.warn('Warning: valid-typeof rule is deprecated. Replace your usage with the TSLint typeof-compare rule.');
        Rule.isWarningShown = true; // <- Inconsistent (few hits, but rarely)
    }
    return this.applyWithFunction(sourceFile, walk); // <- Works almost always (after few rebuilds stopped to work)
}
```

These are simple lines that should definitely hit at least once, but e.g. first line never worked for me.

As workaround I've added `debugger` at top level of the file.
```ts

import { ExtendedMetadata } from './utils/ExtendedMetadata';
debugger;
export class Rule extends Lint.Rules.AbstractRule {
```
rebuild sources and sourcemaps (`npm run tsc:src` for short) and after this "forced" breackpoint all other breakpoints are correctly hit.

@noamyogev84 could you please try same steps and see if this workaround works for you?

**Comment by reduckted** [comment]
> In my case it may work for some lines, and doesn't work for other.

Nice find! I guess I got lucky with what I tried out. I can confirm that it _doesn't_ hit the breakpoints when I put them in any of those places in `validTypeOfRule.ts`.

I took a look at what tslint uses for its debugging of tests, and it appears that the `outFiles` property is required. Using this configuration, the breakpoints are hit:

```json
{
    "type": "node",
    "request": "launch",
    "name": "Run TSLint Tests",
    "program": "${workspaceFolder}/node_modules/tslint/bin/tslint",
    "args": ["--test", "-r", "dist/src", "tests/**"],
    "outputCapture": "std",
    "outFiles": ["${workspaceRoot}/dist/src/**/*.js"],
    "cwd": "${workspaceFolder}",
    "runtimeArgs": ["--nolazy"]
}
```

I've also added the `cwd` and `runtimeArgs` properties that tslint also uses.

**Comment by reduckted** [comment]
> good case study in why VS Code debuggering is still a bit confusing.

Indeed. Not sure why it worked for some files, but failed for others. 

I also discovered that, without `outFiles`, if you put a breakpoint in the compiled JavaScript file, VS Code would hit the breakpoint, but would stop at the corresponding place in the original TypeScript file instead of at the breakpoint in the JavaScript file. 🤯

**Comment by roblourens** [comment]
Glad you figured it out. Any ideas on how I could have made it more obvious? outFiles is not required but it is recommended to be used when possible.

vscode will still load the script's sourcemaps when the script loads, but there is a race between loading the sourcemap and running the line of code with the breakpoint. outFiles lets us pre-load sourcemaps off disk before running the program.

**Comment by JoshuaKGoldberg** [comment]
How about a suggestion for this particular case of not including the `.ts` files? If some or all of these fields aren't filled out (read: if the user is putting breakpoints in a file that won't be included), and the user is placing breakpoints that aren't being hit, maybe some kind of informative dialog?

Right now we just get a generic "breakpoint won't be loaded" complaint without any indication of why., or easy access to the list of files that would be included.

Just a quick thought - seems rather hardcoded to this scenario, and it'd be nice to have a more general solution.

**Comment by roblourens** [comment]
Yeah but I don't know whether anything has actually gone wrong yet, it may be that the file is just not loaded. And if the breakpoint was supposed to be hit, that describes many possible issues with the setup or the sourcemaps.

**Comment by JoshuaKGoldberg** [comment]
> the file is just not loaded

Is there a way we could detect our use case? Suppose you have `source.js` with not-loaded breakpoints along with any (or maybe just both?) of...
* `//# sourceMappingURL=nodes.js.map` that matches up to a neighboring `source.ts`
* A project using TypeScript such as with `tsconfig.json` or an equivalent

**Comment by roblourens** [comment]
The breakpoints will be in `source.ts` (if I understand you correctly) and the whole problem is that it hasn't been associated with a `source.js` file.

If we want to hint that the outFiles field *could* have been used, maybe we would want to detect when a sourcemap is loaded from disk but was not preloaded, then show a hint. But it is kind of specific.
