### ISSUE TITLE
MSE bug: error in walker

### ISSUE THREAD

**Issue by HamletDRC** [Microsoft/tslint-microsoft-contrib#71]
We found an error in PostsContainer.ts

    module PostsContainer {
    
        export interface Props {
            onLoadMore? : () => void;
        }
    
        export class PostsContainer {
            private requestBiggerSet() : void {
                setTimeout(this.props.onLoadMore);
            }
        }
    }

Error: 

>> src/post-interactions/components/PostsContainer.ts[400, 13]: An error occurred visiting a node.
>> Walker: NoStringParameterToFunctionCallWalker
>> Node:
>> // setting to execute after handler. Response may be immediate
>> setTimeout(this.props.onLoadMore)
>> TypeError: Cannot read property 'flags' of undefined

**Comment by loicraux** [comment]
Reproduced an almost similar error with this code :
```typescript
    function wait(millisecs: number): JQueryDeferred<void> {
        return $.Deferred(function (dfd: JQueryDeferred<void>): void {
            setTimeout(dfd.resolve, millisecs);
        });
    }
```

Error :

> >> common/src/tests/common/perf/UserTimingTests.ts[29, 13]: An error occurred visiting a node.
>> Walker: NoStringParameterToFunctionCallWalker
>> Node:
>> setTimeout(dfd.resolve, millisecs)
>> TypeError: Cannot read property 'exports' of undefined

**Comment by slimlime** [comment]
MSE?
Media Source Extensions?
Managed Stack Explorer?
Microsoft Social Engagement project?
