### ISSUE TITLE
Stop including library-specific rules in the recommended ruleset

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/tslint-microsoft-contrib#716]
Spinning off the discussion in #708: enabling the Backbone-related rules in the recommended ruleset is probably just a slight performance tick for the vast majority of users. Can we remove them by default? How about, say, the jQuery rules?

IMO the mocha/chai/etc. test rules should stay in, since that's the general shape of testing APIs in JavaScript test frameworks these days.

**Comment by IllusionMH** [comment]
May be makes sense to provide several configurations (IIRC it is possible, at least TSLint has `all` and `recommended`)?
So migration to next version will require only simple update of configuration to extend to include framework/lib specific checks.

**Comment by VincentLanglet** [comment]
@JoshuaKGoldberg Indeed by creating multiple configuration you don't need for breaking change.

v6 can have tslint-microsoft-config, tslint-microsoft-config:all (doing the same) and tslint-microsoft-config:recommended, and tslint-microsoft-config can be deprecated and removed in v7.

**Comment by VincentLanglet** [comment]
@JoshuaKGoldberg I think the PR does not solve this issue.
For example the backbone related rule is still active.
https://github.com/Microsoft/tslint-microsoft-contrib/pull/809/files#diff-3833edc218170b17d9bac70044d7f313

**Comment by JoshuaKGoldberg** [comment]
Hmm, perhaps this means we should have a `latest` and `all` ruleset split...

**Comment by VincentLanglet** [comment]
Yes, I agree.

- `recommended` is a subset of all rules, minor version doesn't add breaking changes.
- `latest` is the `recommended` rules for the next major version, but still a `subset` of all rules.
- `all` is all.
