### ISSUE TITLE
new rule: unnecessary local variable

### ISSUE THREAD

**Issue by HamletDRC** [Microsoft/tslint-microsoft-contrib#76]
Avoid code like this: 

    var x = something();
    return x;

If a variable declaration is the last line in a statement then just return the previous result.

**Comment by reversi-fun** [comment]
I have question.
Most of the local variable  would  become unnecessary?
Please compare the original  youres code of the following code.
  
+ exsample(1);
../tslint-microsoft-contrib-master/src/noReservedKeywordsRule.ts[44,37]:
/*<Rule>*/ this.applyWithWalker ((new BannedTermWalker((/*Args:*/<any>sourceFile), this.getOptions(), 'Forbidden reference to reserved keyword: ', ['break', 'case', 'catch', 'class', 'const', 'continue', 'debugger', 'default', 'delete', 'do', 'else', 'enum', 'export', 'extends', 'false', 'finally', 'for', 'function', 'if', 'import', 'in', 'instanceof', 'new', 'null', 'return', 'super', 'switch', 'this', 'throw', 'true', 'try', 'typeof', 'var', 'void', 'while', 'with', 'as', 'implements', 'interface', 'let', 'package', 'private', 'protected', 'public', 'static', 'yield', 'any', 'boolean', 'constructor', 'declare', 'get', 'module', 'require', 'number', 'set', 'string', 'symbol', 'type', 'from', 'of'])));

+ exsample(2);
 ../tslint-microsoft-contrib-master/src/noOctalLiteralRule.ts[37.0009]:
/*<NoOctalLiteral>*/ this.createFailure 
((/*Args:*/<any>node).getStart() + (/*Args:*/<any>node).getText().indexOf(/('|')(.*(\\-?[0-7]{1,3}(?![0-9])).*('|'))/g.exec((/*Args:*/<any>node).getText())[3]), /('|')(.*(\\-?[0-7]{1,3}(?![0-9])).*('|'))/g.exec((/*Args:*/<any>node).getText())[3].length, 'Octal literals should not be used: ' + /('|')(.*(\\-?[0-7]{1,3}(?![0-9])).*('|'))/g.exec((/*Args:*/<any>node).getText())[3]);

**Comment by reversi-fun** [comment]
Most of the statements in your code, there is also data showing that it was possible to replace only the description args and class member that does not use a local variable.

https://github.com/reversi-fun/tslint-microsoft-contrib/blob/reversi-fun-patch2/xref/tslint-microsoft-contrib_module.xref_20160119-1152.csv
