### ISSUE TITLE
Add more info about writing new rules to Contribution guidlines

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/tslint-microsoft-contrib#779]
### Feature request

**Is your feature request related to a problem? Please describe.**
`CONTRIBUTING.md` doesn't have information or links to TSLint documentation on how to write custom rules. Only links to testing (for new format) are available ATM.

Better to have all useful for contribution links in `CONTRIBUTING.md`. In this way it will be easier for newcomers to find all necessary info.

**Describe the solution you'd like**
I don't think that there is need to write own guide, but to suggestion check official docs for writing new rules (at least [Custom Rules](https://palantir.github.io/tslint/develop/custom-rules/) and [Performance Tips](https://palantir.github.io/tslint/develop/custom-rules/performance-tips.html))

**Describe alternatives you've considered**
Can't think of anything.

**Additional context**
Suggestion from #770 PR [comment](https://github.com/Microsoft/tslint-microsoft-contrib/pull/770#issuecomment-452718107)

**Comment by JoshuaKGoldberg** [comment]
☠️  *It's time!* ☠️ 

Per #876, this repository is no longer accepting feature pull requests. TSLint is being deprecated and we recommend you switch to https://typescript-eslint.io.

Thanks for open sourcing with us, everyone!
