### ISSUE TITLE
function-name rule has mismatches in options schema/meta, readme description, and actually accepted rules

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/tslint-microsoft-contrib#786]
### Feature request

**Is your feature request that we implement a new rule?**
No

**Is your feature request related to a problem? Please describe.**

1. [README description](https://github.com/Microsoft/tslint-microsoft-contrib/blame/master/README.md#L109-L130) of `function-name` has only description of object with regular expression, but no mention of string flag.

1. `function-name` [rule meta](https://github.com/Microsoft/tslint-microsoft-contrib/blob/1d5b667c8e39c256295b60640f61bb462d9e263d/src/functionNameRule.ts#L47-L71) has only description, schema, and examples of string flags.

1. `function-name` rule schema and examples expect string flags right after `true` that enables rule, but implementation will parse these flags only as second option.

**Describe the solution you'd like**

1. Update `README.md`, rules metadata (options description, schema, and examples) to represent both object and string flags.

1. Update rule options parsing so that string flags can be in first position, if configuration object is not provided (when defaults are OK, but need to control over `static private` validation) 

**Describe alternatives you've considered**

1. Update only `README.md` - this will provide info for end user, but will require some effort and may be missed during implementation of #575 or similar

1. Restrict string flags to second position - is doesn't look great set flag as `[true, {}, "validate-private-statics-as-private"]`

**Additional context**
[Noticed](https://github.com/Microsoft/tslint-microsoft-contrib/pull/665#discussion_r245533499_) in scope of #665

**Comment by JoshuaKGoldberg** [comment]
☠️  *It's time!* ☠️ 

Per #876, this repository is no longer accepting feature pull requests. TSLint is being deprecated and we recommend you switch to https://typescript-eslint.io.

Thanks for open sourcing with us, everyone!
