### ISSUE TITLE
Planning for 6.1.0

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/tslint-microsoft-contrib#788]
Looks like it's been a while since the last release!

* `void-zero` was added by @lizzzp1 
* @drexler and @reduckted have converted most of the rules to the new walker format

Once the rule switching is done, let's release 6.1.0?

Edit: yes!

* #692 adding `react-a11y-iframes` from @noamyogev84

**Comment by IllusionMH** [comment]
Could you take a look at #692?
I think it can be included into `6.1.0` too
