### ISSUE TITLE
Ignore test.each in mocha-no-side-effect-code

### ISSUE THREAD

**Issue by devaradhanm** [microsoft/tslint-microsoft-contrib#812]
### Bug Report

-   **`tslint-microsoft-contrib` version**: 6.0.0
-   **TSLint version**:5.12.1
-   **TypeScript version**:3.2.4

Similar to #545 
```tsx
test.each([1, 2, 3])('some test', (testCase: number) => {
        expect(testCase).toBeDefined();
    });
```

**Comment by IllusionMH** [comment]
Is it Mocha API or some custom module/implementation?

**Comment by devaradhanm** [comment]
Using jest framework

**Comment by JoshuaKGoldberg** [comment]
☠️  *It's time!* ☠️ 

Per #876, this repository is no longer accepting feature pull requests. TSLint is being deprecated and we recommend you switch to https://typescript-eslint.io.

Thanks for open sourcing with us, everyone!
