### ISSUE TITLE
Fix code that should open new files in `create-rule` script

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/tslint-microsoft-contrib#820]
### Feature request

**Is your feature request that we implement a new rule?**
No

**Is your feature request related to a problem? Please describe.**
As was mentioned in #817 - `create-rule` doesn't open newly created files because `VSCODE_CWD` in no longer available in terminals opened from VS Code. Instead it is better to check `TERM_PROGRAM` which was added for this purpose (I think) https://github.com/Microsoft/vscode/commit/9c82ae899c79de07413af7cdbe262dbe4550abd0

**Describe the solution you'd like**
1. Replace check for `VSCODE_CWD` with check if `TERM_PROGRAM` is `vscode` instead.
1. Use [flag `-g`](https://vscode.readthedocs.io/en/latest/editor/command-line/) (or `--goto`) to call VS Code with list of files, instead of separate calls that are much slower (on my machine)
1. Move path with line to `README.md` to the first argument (this is the only way to make VS Code to respect `:line` )

**Describe alternatives you've considered**
Remove code that opened files, but it doesn't looks great if it can be fixed.

**Additional context**
No.

**Comment by JoshuaKGoldberg** [comment]
☠️  *It's time!* ☠️ 

Per #876, this repository is no longer accepting feature pull requests. TSLint is being deprecated and we recommend you switch to https://typescript-eslint.io.

Thanks for open sourcing with us, everyone!
