### ISSUE TITLE
prefer-array-literal: how can one specify the size of the array?

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/tslint-microsoft-contrib#822]
how can one specify the size of the array?

const foo = new Array(10)
?

_Originally posted by @ogiexela in https://github.com/Microsoft/tslint-microsoft-contrib/issues/110#issuecomment-463734744_

**Comment by IllusionMH** [comment]
@ogiexela it depends on case what you want to achieve.

Using `new Array` rarely have any advantages (e.g. it won't create optimized arrays [thread](https://twitter.com/rauschma/status/1066335138798276609)), however behaves differently if there is one or more arguments that leads to errors. Therefore this rule was created.

In general case it is better to use `[]` and fill it with values later (see [thread](https://twitter.com/robpalmer2/status/1064859979897802752)).

If you really need to create array in this way you can disable error for this line with [rule flags](https://palantir.github.io/tslint/usage/rule-flags/) e.g. `// tslint:disable-next-line:prefer-array-literal` on previos line.

**Comment by ogiexela** [comment]
What about the case where I already know the exact size that I need the array to be.
Then according to this per-defined size array performs better.
Or am I missing something?

https://jsperf.com/push-method-vs-setting-via-key/23

![image](https://user-images.githubusercontent.com/29718271/53122001-7d127580-3523-11e9-9e7a-93bd63510bfd.png)

**Comment by IllusionMH** [comment]
It will depend on your use cases. As mentioned in [this tweet](https://twitter.com/mathias/status/1064905990363996160) you see that `new Array` will be faster to create array and fill it with index access.

If your application creates new big arrays really often and usually uses regular `for` loop to iterate though this array - `new Arraly(length)` most likely will be better fo performance.
And you should use `// tslint:disable-next-line:prefer-array-literal` because you are sure that you are passing 1 element and expect to have array of passed length.

However if big arrays are created only once (or in rare ocassions) and app heavily relies on freqest uses  of `.map`, `.forEach` etc. - those loops mig be slower that in case when you use `.push` to keep array packed.

Anyway - if performance is your concern you should check which of these both approaches will be faster in your case.

---

Main reason for this rule - avoid different/unexpected behavior between cases `new Array(1000)`, `new Array(1000, 2000)`, and `new Array('1000')`. And `new Array(length)` has its pros and cons for performance in different cases.

If you need reallocate array - better to disable rule for that single line (only option available ATM).

---

If I understand correctly - similar rule in ESLint (and migrated rule for TS) allows Array constructors with 1 argument. May be makes sense to add flag that will allow this use cases?

@JoshuaKGoldberg what do you think?

**Comment by JoshuaKGoldberg** [comment]
Sure, seems reasonable to add a flag to allow just the case of the constructor with 1 argument. The flag should allow arrays to be created with `new` _only_ when there is a single argument of type `number`.

A few thoughts:
* This requires the type checker, for the case of variables being used instead of literals
* Types that can include non-number types, such as union types and generic types not bound to `extend` a numeric type, should not be allowed:

    ```ts
    // Accidentally creates array of size (item) if TItem is numeric
    function createArrayOfSizeOne<TItem>(item: TItem) {
        return new Array(item);
    }
    ```

**Comment by IllusionMH** [comment]
`6.2.0-beta` was published to npm that allows this behavior.
You can install latest version with `npm install tslint-microsoft-contrib@beta` and list restriction for invocations with single argument with `"prefer-array-literal": [true, {"allow-size-argument": true}]` in your `tslint.json`

**Comment by astorije** [comment]
@IllusionMH, @JoshuaKGoldberg, would you be open to default this parameter to `true`? It seems like a reasonable thing to allow by default.

**Comment by JoshuaKGoldberg** [comment]
@astorije I think so, yeah. Agreed it's reasonable. #678
