### ISSUE TITLE
Moving to ESLint and TSLint deprecation

### ISSUE THREAD

**Issue by cafesanu** [Microsoft/tslint-microsoft-contrib#833]
### Feature request
Given the [TS 2019 roadmap](https://github.com/Microsoft/TypeScript/issues/29288) and the future deprecation of [TSLint](https://github.com/palantir/tslint/issues/4534), I'm wondering if there will be any work in this library to transfer any TSLint rules that still do not exist in ESLint to ESLint.

Thanks

**Is your feature request that we implement a new rule?**
Please use the `Rule Suggestion` template instead

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JoshuaKGoldberg** [comment]
Hey @cafesanu, absolutely! You can see the [typescript-eslint](https://typescript-eslint.io) roadmap here: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md.

There are lists there for both the main TSLint repository and this contrib ruleset.
