### ISSUE TITLE
Update w3 reference in the react-a11y-role rule

### ISSUE THREAD

**Issue by arthurdenner** [Microsoft/tslint-microsoft-contrib#844]
Currently, the `react-a11y-role` rule points to an [old URL](https://www.w3.org/TR/wai-aria/roles#role_definitions) that doesn't exist anymore.

I never saw the previous URL, but I believe the content was the same contained in [this URL](https://www.w3.org/TR/wai-aria-1.1/#role_definitions).

However, we also have [this new URL](https://www.w3.org/WAI/PF/aria/roles#roles_categorization) that seems to contain a more complete explanation about each one of the possible `role` values.

Should we update the URL in the `react-a11y-role` rule? If so, to which URL?

I'd be glad to open a PR with this change, if possible.

**Comment by JoshuaKGoldberg** [comment]
Good catch! Let's go with the apparent new URL, https://www.w3.org/TR/wai-aria-1.1/#role_definitions.
