### ISSUE TITLE
v6.1.0 using deprecated rules

### ISSUE THREAD

**Issue by rbirkgit** [Microsoft/tslint-microsoft-contrib#851]
### Bug Report

-   **`tslint-microsoft-contrib` version**:
6.1.0

-   **TSLint version**:
5.14.0

-   **TypeScript version**:
3.2.4

-   **Running TSLint via**: (pick one) CLI / Node.js API / VSCode / grunt-tslint / Atom / Visual Studio / etc
CLI

#### TypeScript code being linted
with `tslint.json` configuration:

```json

  "extends": [
    "tslint:recommended",
    "tslint-microsoft-contrib",
```

#### Actual behavior

Warning: no-function-constructor-with-string-args rule is deprecated. Replace your usage with the TSLint function-constructor rule.
Warning: no-reserved-keywords rule is deprecated. Replace your usage with the TSLint variable-name rule.
Warning: no-increment-decrement rule is deprecated. Replace your usage with the TSLint increment-decrement rule.
Warning: no-unnecessary-bind rule is deprecated. Replace your usage with the TSLint unnecessary-bind rule.

#### Expected behavior

No usage of deprecated rules

**Comment by IllusionMH** [comment]
@rbirkgit this is intended behavior `tslint-microsoft-contrib` rules list is alias for legacy list, and will remain in this way until next major release to avoid "breaking" projects that don't want to update TSLint core or their configuration. See details here: https://github.com/Microsoft/tslint-microsoft-contrib#legacy

You can use `"tslint-microsoft-contrib/recommended"` (stable list of rules that changes only in major releases) or `"tslint-microsoft-contrib/latest"` (recommended + all new rules added in minor releases)

You can find more information and configs descriptions in [Configuration section](https://github.com/Microsoft/tslint-microsoft-contrib#configuration)

**Comment by rbirkgit** [comment]
Thanks for this explanation. I missed this part!
