### ISSUE TITLE
Planning for 6.3.0

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/tslint-microsoft-contrib#857]
Looks like it's been a while since the last release!

Following #788, what should be in?

- [ ] https://github.com/Microsoft/tslint-microsoft-contrib/issues/432: emojis!
- [ ] A few more rules around a11y would be nice!

**Comment by IllusionMH** [comment]
I'm going to release `6.2.0-beta` tomorrow without mentioned above rules, so this list moves to `6.3.0`

**Comment by JoshuaKGoldberg** [comment]
Hmm, we never did get to this. Ah well...
