### ISSUE TITLE
Support TypeScript 1.7 and tslint 3.2

### ISSUE THREAD

**Issue by reversi-fun** [Microsoft/tslint-microsoft-contrib#87]
when I  try  /tslint-microsoft-contrib-master  "grunt all" ,
then cause Failed:
////
  320 passing (2s)
  1 failing

  1) chaiVagueErrorsRule should pass on xxx:
     AssertionError: Wrong # of failures:
[
  {
    "failure": "An error occurred visiting a node.\nWalker: ChaiVagueErrorsRuleW
alker\nNode: \n            expect(something).to.equal(true, 'message')\nError: u
nsupported ts version on tslint rules",
    "name": "file.ts",
    "ruleName": "chai-vague-errors",
    "startPosition": {
      "character": 13,
      "line": 2
    }
  }
]: expected 0 to equal 1
      at runRuleAndEnforceAssertions (tslint-m
icrosoft-contrib-master\dist\tests\TestHelper.js:58:21)
      at Object.assertViolations (tslint-micro
soft-contrib-master\dist\tests\TestHelper.js:18:9)
      at Context.<anonymous> \tslint-microsoft
-contrib-master\dist\tests\ChaiVagueErrorsRuleTests.js:6:20)

Warning: Task "mochaTest:test" failed. Use --force to continue.

Aborted due to warnings.

////

my modification for TypeScript 1.7.5 is:
//// \tslint-microsoft-contrib-master\src\utils\SyntaxKind.ts ////
    var SyntaxKind_cur: SyntaxKind = { /* 1.7.5 or later */
        /* tslint:enable:variable-name */
        Unknown: ts.SyntaxKind.Unknown,
        EndOfFileToken: ts.SyntaxKind.EndOfFileToken,
        SingleLineCommentTrivia: ts.SyntaxKind.SingleLineCommentTrivia,
        MultiLineCommentTrivia: ts.SyntaxKind.MultiLineCommentTrivia,
        NewLineTrivia: ts.SyntaxKind.NewLineTrivia,
        WhitespaceTrivia: ts.SyntaxKind.WhitespaceTrivia,

..............................
        JSDocTemplateTag: ts.SyntaxKind.JSDocTemplateTag,
        SyntaxList: ts.SyntaxKind.SyntaxList,
        Count: ts.SyntaxKind.Count,
        FirstAssignment: ts.SyntaxKind.FirstAssignment,
..............................
        LastBinaryOperator: ts.SyntaxKind.LastBinaryOperator,
        FirstNode: ts.SyntaxKind.FirstNode
    };
    
    export function current(): SyntaxKind.SyntaxKind {
        if (cachedKinds == null) {
            if (/1\.5\..*/.test(ts.version)) {
                cachedKinds = SyntaxKind_1_5;
            } else if (/1\.6\..*/.test(ts.version)) {
                cachedKinds = SyntaxKind_1_6;
            } else {
                cachedKinds = SyntaxKind_cur; // this is the default for compiler varsion
            }
            if (cachedKinds.SyntaxList !== ts.SyntaxKind["SyntaxList"] ){
               throw new Error("unsupported ts version on tslint rules");
            }
        }
        return cachedKinds;
    }
////

**Comment by HamletDRC** [comment]
What version of tslint and grunt-ts are you using?

**Comment by reversi-fun** [comment]
It seems my tsc1.7.5 support code was incorrect.

And today re-download "tslint-microsoft-contrib-master.zip", I re-try　"grunt all",
 the "Lint is not defined #89"  was reproduced.

I Using 
tsc v1.7.5 
tslint 3.2.1
mocha@2.2.5
grunt-ts@4.2.0
grunt-cli v0.1.13
grunt v0.4.5

-------
"grunt all" results is 
TypeScript compilation complete: 4.67s for 98 typescript files
Running "mochaTest:test" (mochaTest) task
>> Mocha exploded!
>> ReferenceError: Lint is not defined
>>     at Object.<anonymous> (tslint-microsoft
-contrib-master\dist\src\utils\ErrorTolerantWalker.js:31:4)
>>     at Module._compile (module.js:460:26)
>>     at Object.Module._extensions..js (module.js:478:10)
>>     at Module.load (module.js:355:32)
>>     at Function.Module._load (module.js:310:12)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
>>     at Object.<anonymous> (H:\repositories\nodeJS.workspaces\tslint-microsoft
-contrib-master\dist\src\exportNameRule.js:6:27)
>>     at Module._compile (module.js:460:26)
>>     at Object.Module._extensions..js (module.js:478:10)
Warning: Task "mochaTest:test" failed. Use --force to continue.

**Comment by HamletDRC** [comment]
Fixed in master. This is not a backwards compatible change (for now). I will schedule a release. 

thanks for the patience. it was hard to find time during the holiday season.
