### ISSUE TITLE
Adopt commit convention for PR merges

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/tslint-microsoft-contrib#870]
### Feature request

**Is your feature request that we implement a new rule?**
No

**Is your feature request related to a problem? Please describe.**
Creating release notes by hand is long and error prone process now.

**Describe the solution you'd like**
`semantic-release` modules (part of #863) can compile release noted based on commit messages. We need to pick commit message format.
Then as part of PR review process it is possible to rename PR to match picked commit message format (GitHub uses PR name for squash & merge and this will be less error prone) or use proper commit message/body during PR merge.

Main drawback - this isn't automated step and will require manually compose message (using CLI or write an extension)

**Describe alternatives you've considered**
Using same approach as TSLint (see #644) however using single process proposed in #863 looks more easier 

Introducing something like [commitizen](https://commitizen.github.io/cz-cli/) to the project (see [Making your repo Commitizen-friendly](https://github.com/commitizen/cz-cli#making-your-repo-commitizen-friendly) and [Optional: Running Commitizen on `git commit`](https://github.com/commitizen/cz-cli#optional-running-commitizen-on-git-commit)).
Not sure how it will work with multiple commits during code review, not sure if it will be cross platform solution (looking on how to enable it for `git commit`).
This change can be investigated and introduced later.

**Additional context**
N/A

**Comment by IllusionMH** [comment]
Looks like solution will be even easier - Semantic Pull Request bot will track PR names.
Only need to match configurations of `sematic-release` and Semantic Pull Request bot.

**Comment by JoshuaKGoldberg** [comment]
☠️  *It's time!* ☠️ 

Per #876, this repository is no longer accepting feature pull requests. TSLint is being deprecated and we recommend you switch to https://typescript-eslint.io.

Thanks for open sourcing with us, everyone!
