### ISSUE TITLE
Reconsider approach for beta versions releases

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/tslint-microsoft-contrib#871]
### Feature request

**Is your feature request that we implement a new rule?**
No

**Is your feature request related to a problem? Please describe.**
Releases of separate version with `-beta` suffix in NPM takes time and promotion to stable release requires re-release same code with only version change and duplication in release notes.

**Describe the solution you'd like**
Maybe using `beta` dist-tag on npm will be enough?
If we want to introduce more or less automated releases as described in #863 it is possible to configure package publishing using [`tag` in `.npmrc` or `package.json`](https://github.com/semantic-release/npm#npm-configuration). In this way all versions will be published with `beta` tag and it is pretty easy to promote it to `latest` without need for new release, updates to change log etc.

Possible drawbacks - merging commits with fix for `beta` version and/or other PRs.
Depending on what PRs was merged it might be patch version (I see no problem with releasing `6.3.2` instead of `6.3.0` to stable) or minor version (not a big problem, but might look sub-optimal). In later case we can wait to promote `beta` to `latest` and then merge all other feature commits.

**Describe alternatives you've considered**
As described in https://github.com/microsoft/tslint-microsoft-contrib/issues/863#issuecomment-493758762 `semantic-release` can add `-beta` prefix if we'll use branches, however I think that it will require unnecessary confusion for contributors as well as efforts to manage branches and direct PRs to proper branch.

**Additional context**
N/A

**Comment by IllusionMH** [comment]
OK to use just `beta` dist-tag for patch and minor versions. Will looks at the situation for major.

**Comment by JoshuaKGoldberg** [comment]
☠️  *It's time!* ☠️ 

Per #876, this repository is no longer accepting feature pull requests. TSLint is being deprecated and we recommend you switch to https://typescript-eslint.io.

Thanks for open sourcing with us, everyone!
