### ISSUE TITLE
$(()=>{}) flags no-jquery-raw-elements

### ISSUE THREAD

**Issue by kasugaiasuka** [microsoft/tslint-microsoft-contrib#872]
### Bug Report

-   **`tslint-microsoft-contrib` version**: 6.2.0
-   **TSLint version**: 5.16.0
-   **TypeScript version**: 3.4.5
-   **Running TSLint via**: CLI

#### TypeScript code being linted

```tsx
$(async () => {

})
```

with `tslint.json` configuration:

```json
{
    "defaultSeverity": "error",
    "extends": [],
    "jsRules": {},
    "rules": {
        "no-jquery-raw-elements": true
    },
    "rulesDirectory": [
        "node_modules/tslint-microsoft-contrib"
    ]
}
```

#### Actual behavior
```
(Error:no-jquery-raw-elements) Replace HTML string manipulation with jQuery API: $(async () => {

})
```

#### Expected behavior
No errors.
FYI, tslint-microsoft-contrib@6.1.1 is working properly.

**Comment by kasugaiasuka** [comment]
Oops, that is not a minimum code ("async" is not needed.)

```
$(() => {

});

// Replace HTML string manipulation with jQuery API: $(() => {
// 
// })
```

**Comment by IllusionMH** [comment]
Looks like regression after migration to the new format.

Previously if first arguments wasn't a string - new walker was created and recursively checked strings for `<` or `>` characters **in string literals**, however new one looks for same characters in any expression text.

Good solution will be to check if first argument is a function expression or an arrow function, and only then check recursively as it was in old implementation.

Accepting PRs

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is deprecated** and no longer accepting pull requests other than security fixes. See #876. ☠️ 
We recommend you instead use **[typescript-eslint](https://typescript-eslint.io)** to lint your TypeScript code with **ESLint**. ✅

👋 It was a pleasure open sourcing with you!
