### ISSUE TITLE
Roadmap: tslint-microsoft-contrib -> ESLint

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/tslint-microsoft-contrib#876]
TSLint is being deprecated soon: see https://github.com/palantir/tslint/issues/4534.

> As you may have read in  [this blog post](https://medium.com/palantir/tslint-in-2019-1a144c2317a9), we plan to deprecate TSLint in 2019 and support the migration to ESLint as the standard linter for both TypeScript & JavaScript. This will not be an immediate deprecation; on the contrary, there is a lot of work to do to ensure a smooth transition to the new tooling without any regressions. 

tslint-microsoft-contrib will follow the timeline in that issue. We'll continue accepting classifications of issues and pull requests, such as new rules, features, and bug fixes, on the same timeline as TSLint. The timeline is:

- __August 1st, 2019__: Stop accepting new _core_ rules. Still accept bug fixes, minor features, and rule enhancements. Custom rules are always an option and can be maintained outside this repo.
- __November 1st, 2019__: Stop accepting features or rule enhancements (with the exception of ones that make migrating to typescript-eslint easier). Still accept bug fixes.
- __January 1st, 2020__: Stop accepting anything except security fixes.
- __December 1st, 2020__: Stop accepting any PRs 🎉

---

Update (August 2019): see **[tslint-to-eslint-config](https://github.com/typescript-eslint/tslint-to-eslint-config)** for a CLI command that migrates TSLint configuration files to ESLint configuration files.

**Comment by JoshuaKGoldberg** [comment]
Copying a couple FAQs from the other issue:

**How can I use existing TSLint rules in ESLint?**

You can use your TSLint rules within ESLint using [typescript-eslint/packages/eslint-plugin-tslint](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin-tslint). It wraps a TSLint configuration and lints your code using TSLint.

**How can I write TypeScript-capable rules in ESLint?**

To write rules in ESLint, see [typescript-eslint/packages/eslint-plugin](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin). That README.md has a list of all their supported rules _(the list has gotten pretty big!)_. The [ROADMAP.md](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md) there has a mapping of existing TSLint rules to the new equivalents.

**Comment by AndrewCraswell** [comment]
In the future, do you imagine the `tslint-microsoft-contrib` can be consumed in ESLint without using the `eslint-plugin-tslint`?

**Comment by JoshuaKGoldberg** [comment]
@AndrewCraswell alas, no, such a thing is not technically feasible. This library is a collection of TSLint rules, and `eslint-plugin-tslint` is _the_ way for consuming (running) rules in ESLint.

**Comment by lumaxis** [comment]
Are there any plans for a `eslint-microsoft-contrib` package or some such?

**Comment by JoshuaKGoldberg** [comment]
@lumaxis no, no plans. Unlike TSLint, ESLint's community is rich and thriving; there'd be no need. 😄

**Comment by IllusionMH** [comment]
You can check roadmap for TSLint rules in typescript-eslint repo: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md#tslint-microsoft-contrib-rules

It has list of corresponding ESLint rules or ESLint plugins that implement similar functionality to existing rules.
Most likely rules from this repo with hight demand/usability can be added to typescript-eslint package, so discussions for concrete rules can be started there (if not started already).

**Comment by brndkfr** [comment]
This project is read-only and [archive](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-archiving-repositories) mode.
