### ISSUE TITLE
react-no-dangerous-html threw an error

### ISSUE THREAD

**Issue by cyberhck** [microsoft/tslint-microsoft-contrib#880]
Not sure if this is a bug, design decision or something changed in tslint parsing of options.

I had part of tslint.json like this:
```json
    "react-no-dangerous-html": [
      true,
      {
        "file": "./src/app/containers/Html.tsx",
        "method": "render",
        "comment": "string comes from trusted source - our initial state"
      }
    ]
```
I got error which said: "`ctx.options.exceptions.forEach` is not a function" I did some debugging by adding `console.log`s into `node_modules/tslint-microsoft-contrib/...` and figured something has changed, I just updated `tslint-microsoft-contrib` so it's safe to say I'm definitely on latest version as of now.

I did find a workaround:
```json
    "react-no-dangerous-html": [
      true,
      [
        {
          "file": "./src/app/containers/Html.tsx",
          "method": "render",
          "comment": "string comes from trusted source - our initial state"
        }
      ]
    ]
```
which is basically wrapping in an array of which now makes sense but I couldn't find any documentation on this. Wiki page still shows the old style (the one I posted earlier)

I just want to know if this is a bug in this repo or signature has changed so I'd know how to move forward.

Thanks.

**Comment by IllusionMH** [comment]
@cyberhck rule was migrated to new rule format, but I don't think that change was intentional. Will need to look closer what actually changed in options parsing logic, since checks for `instanceof Array` are still in place.

Thanks for reporting.

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is deprecated** and no longer accepting pull requests other than security fixes. See #876. ☠️ 
We recommend you instead use **[typescript-eslint](https://typescript-eslint.io)** to lint your TypeScript code with **ESLint**. ✅

👋 It was a pleasure open sourcing with you!
