### ISSUE TITLE
Relax the no-void-expression configuration for arrow functions

### ISSUE THREAD

**Issue by astorije** [microsoft/tslint-microsoft-contrib#885]
Using the recommended ruleset, the [`no-void-expression`](https://palantir.github.io/tslint/rules/no-void-expression/) rule is enforced ([here](https://github.com/microsoft/tslint-microsoft-contrib/blob/bfc28e95dde1fab92aa457e79d338fb03b81d7cc/build-tasks/back-compat/recommended_ruleset.js#L159)).

With the recent addition of React Hooks, in particular the [`useState`](https://reactjs.org/docs/hooks-state.html) hook, inlining arrow function has become a lot more frequent. Documentations such as the React doc itself, or Apollo tutorials [such as this one](https://blog.apollographql.com/apollo-client-now-with-react-hooks-676d116eeae2) use this to make things more concise and palatable.

For example, this format is pretty accepted and convenient:

```tsx
export const ModalContainer: React.FunctionComponent = props => {
  const [open, setOpen] = React.useState<boolean>(false);

  return <Modal open={open} onClose={() => open(false)} />;
};
```

(Of course this is just a dumb example, do not challenge me on the why and how of that made up `Modal` interface lol)
The default ruleset enforces writing this as:

```tsx
return <Modal open={open} onClose={() => { open(false); }} />
```

Which Prettier (and maybe this ruleset as well? I am not sure as we have disabled stylistic rules in favor of Prettier) formats it on a dedicated line:

```tsx
return (
  <Modal
    open={open}
    onClose={() => {
      open(false);
    }}
  />
);
```

This becomes a little tedious. Would you be open to having the default ruleset be a little more flexible about this?

We are currently adding the following override to our configuration:

```yaml
no-void-expression:
  - true
  - ignore-arrow-function-shorthand
```

But we think it would be an acceptable default for the recommended ruleset (and would not introduce a breaking change).

**Comment by JoshuaKGoldberg** [comment]
☠️  *It's time!* ☠️ 

Per #876, this repository is no longer accepting feature pull requests. TSLint is being deprecated and we recommend you switch to https://typescript-eslint.io.

Thanks for open sourcing with us, everyone!
