### ISSUE TITLE
static-method-regex should be PascalCase, not UPPERCASE

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/tslint-microsoft-contrib#899]
### Rule Suggestion

**Is your rule for a general problem or is it specific to your development style?**
I have not seen any libraries that use uppercase for static methods, however I believe that PascalCase is quite standard for static methods.
 
The current regex is: 
https://github.com/microsoft/tslint-microsoft-contrib/blob/master/src/functionNameRule.ts#L77
`let staticMethodRegex: RegExp = /^[A-Z_\d]+$/;`

Honestly I think this is a bug but I'd like to have the discussion.

**Comment by JoshuaKGoldberg** [comment]
:wave: @danmarshall, ☠️  **TSLint is deprecated** ☠️  and we strongly suggest switching  to **https://typescript-eslint.io**. tslint-microsoft-contrib is no longer accepting feature requests or bug reports for issues that are not critical security or TypeScript compatibility failures.

Happy linting!

**Comment by JoshuaKGoldberg** [comment]
https://github.com/palantir/tslint/issues/4534
