### ISSUE TITLE
Won't add rules to linting process.

### ISSUE THREAD

**Issue by cerebrl** [Microsoft/tslint-microsoft-contrib#90]
TSLint works fine, but it won't pick up the rules supplied by this module. Here's what I've done:

1. `npm install tslint-microsoft-contrib --save-dev`
2. Tried multiple ways of adding the rules directory:
    1. In `tslint.json` added "rulesDirectory": "node_modules/tslint-microsoft-contrib" as a root property.
    2. In `package.json`, where I'm running this as a NPM script to the `script` property, I wrote `tslint --rules-dir node_modules/tslint-microsoft-contrib index.js`
3. Added the flags to the `tslint.json` file that this module provides within the `rules` property.

The bottom line, I could not get this to work for the life of me using this within an NPM script. Is that what the problem is? Can you just not pick these rules up from with the context of running this within NPM? Any help would be appreciated. Thanks.

**Comment by HamletDRC** [comment]
I am doing this in my grunt build. 

Here is my directory layout: 

    myapp
    -->node_modules
        --> tslint-microsoft-contrib
    -->Gruntfile.js

Inside Gruntfile.js I have configured: 

            options: {
                rulesDirectory: rulesDir,
                configuration: grunt.file.readJSON(ruleFile)
            },

Where do you configure tslint to run? Are you using Grunt?

**Comment by cerebrl** [comment]
Thanks for the reply. I'm not using Grunt but using the NPM `scripts` within `package.json`, so when I run it, I just run the command `npm run lint`, and that in turn runs the `tslint` CLI command.

**Comment by HamletDRC** [comment]
Can you post your package.json file?

**Comment by janjarfalk** [comment]
I have the same problem and I just created a repo where it manifests.

Here is my package.json:
https://github.com/janjarfalk/ionic2-angular2-typescript-boilerplate/blob/master/package.json

Here is my tslint.json:
https://github.com/janjarfalk/ionic2-angular2-typescript-boilerplate/blob/master/tslint.json

The `"export-name`-rule is not picked up.

**Comment by HamletDRC** [comment]
You specify the rules directory on the command line using the -r option. 

So your scripts tag should be something like this: 

      "scripts": {
        "lint": "tslint -s tslint/formatters -t color --config tslint.json app/**/*.ts -r node_modules/tslint-    microsoft-contrib/",
        "validate": "npm ls"
      },

Please note, I changed your {apps,pages} to be ** in order to get the rules to run at all. I think the globbing is not what you expect as well. 

I tested this by putting a console message in exportNameRule.js and then running the linter. I saw the warnings, so it worked.

**Comment by HamletDRC** [comment]
Also, I am more than happy to help here but technically this was a tslint question. If my response time is too long then you can try the tslint chatroom. They typically respond within a day (and might be in your timezone which also helps with response times). Good luck!

**Comment by janjarfalk** [comment]
Thanks for your help, but I'm not sure the exportNameRule is working properly.
If add two console.log messages to the exportNameRule file like this:
```
function ExportNameWalker() {
  console.log('A');
  _super.apply(this, arguments);
}
ExportNameWalker.prototype.visitExportAssignment = function (node) {
  console.log('B');
  ...
}
```
It logs A, but never B and it doesn't throw any warnings.

**Comment by HamletDRC** [comment]
It never logs 'B' because none of your exports are in the 'export = ExportName' format. 

If you change page1.ts to be: 

    export = Page1;

then it fails with the error: 
  
    -- [17, 10] - The exported module name must match the file name. Found: app/pages/page1/page1.ts and Page1


because page1 does not equal Page1

I assume you want your page1.ts and Page class inconsistency to be flagged, so I went ahead and created an issue in our system to find usages where there is only 1 exported entity from a file and it does not match the filename (#93)

**Comment by janjarfalk** [comment]
Ah, I see!
You assume correct.
Thanks for your help!
Looking forward to #93

**Comment by cerebrl** [comment]
Just in case someone else runs across this issue, the problem was from having the `"rulesDirectory"` property within the `tslint.json` file. Just use the `-r` command to point to the additional rules, and you should be good.
