### ISSUE TITLE
ScopedSymbolTrackingWalker.typeChecker  returns undefined

### ISSUE THREAD

**Issue by reversi-fun** [Microsoft/tslint-microsoft-contrib#94]
I seems that ScopedSymbolTrackingWalker.typeChecker is incomplete.

I tried to make　NoCookiesWalker　at ScopedSymbolTrackingWalker.
-- cd tslint-microsoft-contrib-master
-- tslint -r dist\src test-data/NoCookiesPassingTestInput.ts

it causes error;

    test-data/NoCookiesPassingTestInput.ts[2, 11]: An error occurred visiting a node.
    Walker: NoCookiesWalker
    Node:  DocumentLikeAPI
    TypeError: Cannot read property 'flags' of undefined
    test-data/NoCookiesPassingTestInput.ts[3, 5]: An error occurred visiting a node.
    Walker: NoCookiesWalker
    Node: 
        cookie
    TypeError: Cannot read property 'flags' of undefined
    test-data/NoCookiesPassingTestInput.ts[6, 10]: An error occurred visiting a node.
    Walker: NoCookiesWalker
    Node:  documentLikeAPIFunction
    TypeError: Cannot read property 'flags' of undefined
    test-data/NoCookiesPassingTestInput.ts[11, 5]: An error occurred visiting a node.
    Walker: NoCookiesWalker
    Node:  document
    TypeError: Cannot read property 'flags' of undefined

**Comment by reversi-fun** [comment]
My workaround is as follows:
(a) compilerOptions.noResolve = false. ant it is own instance. 
  compilerOptions = <ts.CompilerOptions>{ target: ts.ScriptTarget.ES5, module: ts.ModuleKind.CommonJS, noResolve: false};

(b)  curTypeChecker create from (a), not  from languageService ;
(c)  sourceFile re-create from (a),not TSLINT instance.

//
import * as ts from 'typescript';
import * as Lint from 'tslint/lib/lint';

import ErrorTolerantWalker = require('./utils/ErrorTolerantWalker');
import ScopedSymbolTrackingWalker = require('./utils/ScopedSymbolTrackingWalker');
import AstUtils = require('./utils/AstUtils');

/**
 * Implementation of the no-cookies-rule rule.
 */
export class Rule extends Lint.Rules.AbstractRule {
    public static FAILURE_STRING = 'Forbidden call to document.cookie';

    public apply(sourceFile : ts.SourceFile): Lint.RuleFailure[] {
        var compilerOptions: ts.CompilerOptions ;
        //compilerOptions = Lint.createCompilerOptions();
        //compilerOptions.module = ts.ModuleKind.CommonJS;
        //compilerOptions.noResolve = false;
        compilerOptions = <ts.CompilerOptions>{ target: ts.ScriptTarget.ES5, module: ts.ModuleKind.CommonJS, noResolve: false};
        var curProgram: ts.Program = ts.createProgram([sourceFile.fileName],compilerOptions);
        var curTypeChecker: ts.TypeChecker = curProgram.getTypeChecker();
        
        var documentRegistry = ts.createDocumentRegistry();
        var languageServiceHost = Lint.createLanguageServiceHost('file.ts' /* sourceFile.fileName*/, sourceFile.getFullText());
        var languageService : ts.LanguageService = ts.createLanguageService(languageServiceHost, documentRegistry);
        //return this.applyWithWalker(new NoCookiesWalker(sourceFile, this.getOptions(), languageService));
        //return this.applyWithWalker(new NoCookiesWalker(sourceFile, this.getOptions(), languageService, curTypeChecker)); //workarounds failed
        return this.applyWithWalker(new NoCookiesWalker(curProgram.getSourceFile(sourceFile.fileName), this.getOptions(), languageService, curTypeChecker)); //workarounds
    }
}

class NoCookiesWalker extends ScopedSymbolTrackingWalker /* ErrorTolerantWalker Lint.RuleWalker*/ {

    //protected languageServices : ts.LanguageService; // from ScopedSymbolTrackingWalker
    //protected typeChecker : ts.TypeChecker; // from ScopedSymbolTrackingWalker

    constructor(sourceFile: ts.SourceFile, options: Lint.IOptions, languageService : ts.LanguageService, /*workarounds*/ typeChecker : ts.TypeChecker) {
        //super(sourceFile, options);
        super(sourceFile, options , languageService);
        this.languageServices = languageService;
        //this.typeChecker = languageService.getProgram().getTypeChecker(); /*workarounds*/
        this.typeChecker = typeChecker; /*workarounds*/
    }


    protected visitPropertyAccessExpression(node: ts.PropertyAccessExpression): void {
        var propertyName = node.name.text;
        if (propertyName === 'cookie') {

            var leftSide : ts.Expression = node.expression;
            try {
                var leftSideType: ts.Type = this.typeChecker.getTypeAtLocation(leftSide);
                var typeAsString: string = this.typeChecker.typeToString(leftSideType);
                if (leftSideType.flags === ts.TypeFlags.Any || typeAsString === 'Document') {
                    this.addFailure(this.createFailure(leftSide.getStart(), leftSide.getWidth(), Rule.FAILURE_STRING));
                }
            } catch (e) {
                // TODO: this error seems like a tslint error
                if (leftSide.getFullText().trim() === 'document') {
                    this.addFailure(this.createFailure(leftSide.getStart(), leftSide.getWidth(), Rule.FAILURE_STRING));
                }
            }
        }

        super.visitPropertyAccessExpression(node);
    }
    protected visitIdentifier(node: ts.Identifier): void {
        super.visitIdentifier(node);
        AstUtils.dumpTypeInfo(node, this.languageServices, this.typeChecker);
    }
}

**Comment by reversi-fun** [comment]
In AstUtils.dumpTypeInfo (node, this.languageServices, this.typeChecker), 
I found the following.

for DocumentLikeAPI missing
	typeChecker.typeToString : DocumentLikeAPI
	type.flags: 2048
	type.symbol: [object Object]
	symbol.flags: 64
	symbol.name: DocumentLikeAPI
	symbol.declarations: [object Object]
	contextualType: undefined

for cookie missing
	typeChecker.typeToString : string
	type.flags: 2
	type.symbol: undefined
	symbol.flags: 4
	symbol.name: cookie
	symbol.declarations: [object Object]
	contextualType: undefined

for documentLikeAPIFunction missing
	typeChecker.typeToString : () => DocumentLikeAPI
	type.flags: 65536
	type.symbol: [object Object]
	symbol.flags: 16
	symbol.name: documentLikeAPIFunction
	symbol.declarations: [object Object]
	contextualType: undefined

**Comment by HamletDRC** [comment]
Can you post the code that was being analyzed? 
Also, if you indent all sample code with 4 spaces then the code will be formatted.

**Comment by HamletDRC** [comment]
This looks very promising to solve several of our issues!

**Comment by reversi-fun** [comment]
I beg forgiveness from you to The awkwardness of how to using my github.
The reason is because my organization of proxy does not allow the upload of binary(tab-char or other). 

>Is there any chance you can send a pull request?
I  can only an short  text post.
Do you can receive this URL code?

https://github.com/reversi-fun/tslint-microsoft-contrib/blob/no-function-expression/src/noCookiesRule.ts

https://github.com/reversi-fun/tslint-microsoft-contrib/blob/no-function-expression/src/ScopedSymbolTrackingWalker.ts

I have also attempted to enable inherit ScopedSymbolTrackingWalker.

**Comment by reversi-fun** [comment]
Do you, in order to TypeScript-type resolution(compilerOptions.noResolve = false),
has confirmed that the following need?
(a) there is a need for all the relevant files needed to compile.
  exsample using  AngularJS based application.
 
(b) for the specific tslint-rule implementation of (a), as in the "files" property of tsconfig.json, it requires a list of related files.

(c) (b) is, by calling also three times tsc compiler, to very slow tslint.

(d) reasons(c), a particular tslint-rule implemented only needs to be capable of (a).

I hope your's discussions with tslint team.

**Comment by reversi-fun** [comment]
Scope SymbolTrackingWalker is a very useful TypeScriptLanguageService API sample code.

It is also useful to make a cross-reference data as Following.
I  expect  to Your's work, in order to be able to use the more easily scope, 

https://github.com/reversi-fun/tslint-microsoft-contrib/blob/reversi-fun-patch2/xref/tslint-microsoft-contrib_module.xref_20160119-1152.csv

https://github.com/reversi-fun/tslint-microsoft-contrib/blob/reversi-fun-patch2/xref/ScopedSymbolTrackingWalker_.xref_20160119-1246.csv

**Comment by reversi-fun** [comment]
I have mixed even this workaround and "Reversi fun patch2 #111".
https://github.com/Microsoft/tslint-microsoft-contrib/pull/111

So, hope to you, that  reopen the issue(new rule: "Incomplete property Object at calling" pull request. #97).
https://github.com/Microsoft/tslint-microsoft-contrib/issues/97

**Comment by reversi-fun** [comment]
I have seen that it is a delicate.
>(a) compilerOptions.noResolve = false.
>(b) for the specific tslint-rule implementation of (a), as in the "files" property of tsconfig.json, it requires a list of related files.

 ["Add support for tsconfig.json #281"](https://github.com/palantir/tslint/issues/281)
[Supply files to lint in tsconfig.json #858](https://github.com/palantir/tslint/issues/858)
[Lint doesn't not check files #378](https://github.com/AngularClass/angular2-webpack-starter/issues/378)

Do you feel how about this TSLint-issues ?
