### ISSUE TITLE
new rule: "Incomplete property Object at calling"  pull request.

### ISSUE THREAD

**Issue by reversi-fun** [Microsoft/tslint-microsoft-contrib#97]
I was try to make a prototype　a new rule
as  "Incomplete property Object at calling" ,
and "Vauge property Object at calling".

I think  that's effective to check the Model layer in the MVC or MVP.
I　hope re-implementation　 to people who can respond to changes in the New versions and the diverse version of TypeScript. 

(a) "Incomplete property Object at calling"
  when argument of callExpression was the interface of 101 properties, 
if only 100 properties have not been assigned, and then reports  that it is not enough.
It gives a warning　 to those who believe that ”just hundred is good” .
>  interface IRecord{
    a:string; b:number ; c? : any; junc:any;
  }
  var d = &lt; IRecord &gt; {};
  d.a = "one"; 
  callFunc(d); // error becouse d.b is undefind
  d.b = 2;  // d.junc is undefine yet 
  callFunc(d) // ok 
>

  supress Error fot optional property(d.c) or exceps-specified name property(d.junc). 
restful resource contains a lot of property to the communication message of json format.
Therefore,we leak as described above is liable to occur.

  exsample of tslint.json Option:
>    "ng-Incomplete-Object": [true,
        {"callNames":["'$http'.get","'$http'.put","'$http'.post","'RestResource'.postHttp","delete"],
         "exceptNames":["junc", "filler","yobi"],
         "valueExpand": true,
         "CheckVauge": true
>        }]

(b) "Vauge property Object at calling".
  it encourage the "single assignment" of a function-oriented design.
  example;
>  {
   if(flag) a=1;
   else a=0;
   callFunc(a);
>  }

  above code let Vauge Value a={|1 |,| 0|}  at  "callFunc.args[0]".
>  {a= (flag ? 1: 0);  callfunc(a); }

  above code is not Vauge Value at calling "callFunc.args[0]".
  Data conversion in model layer is desirable to be unified into one unit. 
Therefore, following code is better code.
>{
    a = booltoNumberConverter(flag);
    callfunc(a);
>}

Detailed execution example, please refer to the following.
https://github.com/reversi-fun/tslint-microsoft-contrib/blob/reversi-fun-patch2/test-data/ngIncompleteObjectFailingTestInput.ts

https://github.com/reversi-fun/tslint-microsoft-contrib/blob/reversi-fun-patch2/test-data/ngIncompleteObjectFailingTestOutput.txt

please refer to the following my code.
https://github.com/reversi-fun/tslint-microsoft-contrib/blob/reversi-fun-patch2/src/ngIncompleteObjectRule.ts

**Comment by HamletDRC** [comment]
I am sorry, but the failure scenarios are unclear. Can you please send a pull request?

**Comment by reversi-fun** [comment]
Oh! 2mounth later..

I send " Pull Request #111 Reversi fun patch2".  

can You read flowing:
・src/ngIncompleteObjectRule.ts
・test/ngIncompleteObjectFailingTestInput.ts
・test/ngIncompleteObjectFailingTestOutput.txt

**Comment by reversi-fun** [comment]
tslint.json  for my   "Incomplete property Object at calling"  and  test/ngIncompleteObjectFailingTestInput.ts.
//
   "ng-Incomplete-Object": [true,
        {"callNames":["'$http'.get","'$http'.put","'$http'.post","'$http'.delete","'Rest'.postHttp","delete"],
         "exceptNames":["junc", "filler","yobi"]
        }],
//
--"callNames": what call Expression to be Checks?.
-- "exceptNames": what properties name prefix  in object will be except?.
-- "valueExpand": wants expands values in tslint messages?.
-- "CheckVauge": wants Vague vales?.
