### ISSUE TITLE
validTypeofRule.ts too slow

### ISSUE THREAD

**Issue by reversi-fun** [Microsoft/tslint-microsoft-contrib#98]
When tslint -validTypeofRule.ts　apply to my code, tslint became very slow.

when "valid-typeof": true;
 "grunt all" runs over 30 Minutes.

https://github.com/reversi-fun/tslint-microsoft-contrib/blob/reversi-fun-patch2/test-data/valid-typeof_too_slow.txt

when "valid-typeof": false;
 "grunt all" runs about  3 Minutes.
https://github.com/reversi-fun/tslint-microsoft-contrib/blob/reversi-fun-patch2/test-data/valid-typeof_disavled_run.txt

my code is;
https://github.com/reversi-fun/tslint-microsoft-contrib/blob/reversi-fun-patch2/src/ngIncompleteObjectRule.ts

**Comment by HamletDRC** [comment]
Great... i will look into this on the weekend!

**Comment by reversi-fun** [comment]
I'm  try to fix.
"grunt all" is sucess and e-time is "tslint:files    3m 17.5s ".

Prease see:
https://github.com/reversi-fun/tslint-microsoft-contrib/blob/reversi-fun-patch2/src/validTypeofRule.ts

**Comment by HamletDRC** [comment]
I tried to profile these two functions and I don't see much of a different. 
Hamming is 3.4 seconds and levenstein is 3.5

https://jsfiddle.net/gcLqeqvr/

**Comment by reversi-fun** [comment]
I See your's Data.
Youres "Hamming function" is used ”Recursive call". It is that's slow cause.

Please try to apply to the my code:
https://github.com/reversi-fun/tslint-microsoft-contrib/blob/reversi-fun-patch2/src/ngIncompleteObjectRule.ts

By the way ,youres test code is incorrect, and collect code is too slow.
https://jsfiddle.net/gcLqeqvr/
>>
var start = new Date().getTime();
for (var x = 0; x < 1000000; x++) {
   hammingDistance('value', 'value' + x);  // Not  levenshteinDistance('value', 'value' + x);
}
var end1 = new Date().getTime();
for (var y = 0; y < 1000000; y++) {
    levenshteinDistance('value', 'value' + y);
}
var end2 = new Date().getTime();
>>

**Comment by HamletDRC** [comment]
ok, yes I had an error. I will update this.

**Comment by reversi-fun** [comment]
Also in a different Node.js environment , you can reproduce the slowness.
http://ideone.com/lwoIUa

 levenshteinDistance=6387 m Sec
hammingDistance=1637 *1000 m Sec

34.for (var x = 0; x < 1000000; x++) {
35.    levenshteinDistance('value', 'value' + x);
36.}
37.var end1 = new Date().getTime();
38.for (var y = 0; y < 1000; y++) {
39.    hammingDistance('value', 'value' + y);
40.}
